(function(root){
'use strict';
const subjects=[{id:'maths',name:'Math workshop',icon:'＋',color:'#eea05a',desc:'Build it. Solve it. Explain it.'},{id:'reading',name:'Reading & phonics',icon:'Aa',color:'#75ad80',desc:'Sounds, words, and wonderful stories.'},{id:'scienceLab',name:'Science lab',icon:'⚗',color:'#71aabb',desc:'Predict, observe, and discover.'},{id:'history',name:'Time travelers',icon:'⌛',color:'#b299cd',desc:'Explore people, evidence, and the past.'},{id:'geography',name:'Planet explorers',icon:'◎',color:'#699e86',desc:'Maps, places, and our connected world.'}];
const mathSpecs=[
[['count','Counting to 10','Count each object once.','K.CC.B.4'],['add','Putting groups together','Represent addition with objects.','K.OA.A.1'],['sub','Taking some away','Represent subtraction with objects.','K.OA.A.1'],['compare','More, less, equal','Compare two numbers from 1 to 10.','K.CC.C.7'],['ten','Make a ten','Find the partner that makes ten.','K.OA.A.4'],['shape','Shape detectives','Name familiar two-dimensional shapes.','K.G.A.2']],
[['add','Addition within 20','Use making ten to add.','1.OA.C.6'],['sub','Subtraction within 20','Use the connection between adding and subtracting.','1.OA.C.6'],['place','Tens and ones','Read two-digit numbers as tens and ones.','1.NBT.B.2'],['add2','Add tens and ones','Combine tens with tens and ones with ones.','1.NBT.C.4'],['compare','Compare two-digit numbers','Compare tens first, then ones.','1.NBT.B.3'],['clock','Time to the hour','Connect a clock time to hours and minutes.','1.MD.B.3']],
[['add2','Two-digit addition','Regroup ten ones into one ten.','2.NBT.B.5'],['add3','Three-digit addition','Add hundreds, tens, and ones.','2.NBT.B.7'],['sub','Subtract with regrouping','Trade a ten for ten ones when needed.','2.NBT.B.7'],['place','Hundreds, tens, ones','Explain the value of each digit.','2.NBT.A.1'],['array','Equal rows','Count objects arranged in equal rows.','2.OA.C.4'],['money','Count the coins','Find the total value of US coins.','2.MD.C.8'],['length','Measuring and comparing','Compare lengths in the same unit.','2.MD.B.5']],
[['mul','Multiplication groups','Connect equal groups to multiplication.','3.OA.A.1'],['div','Division as sharing','Split a total into equal groups.','3.OA.A.2'],['fraction','Fractions are equal parts','Name a fraction of a whole.','3.NF.A.1'],['area','Cover an area','Multiply rows and columns of unit squares.','3.MD.C.7'],['perimeter','Around the outside','Add the side lengths of a shape.','3.MD.D.8'],['add3','Add within 1,000','Use place value to explain addition.','3.NBT.A.2'],['elapsed','Time passes','Find elapsed time in minutes.','3.MD.A.1']],
[['mul2','Multiply larger numbers','Use partial products to multiply.','4.NBT.B.5'],['div','Divide larger numbers','Connect division to equal groups and multiplication.','4.NBT.B.6'],['remainder','What is left over?','Interpret a quotient and remainder.','4.NBT.B.6'],['equiv','Equivalent fractions','Scale numerator and denominator together.','4.NF.A.1'],['fracadd','Add like fractions','Add equal-sized fractional parts.','4.NF.B.3'],['add3','Add bigger numbers','Use a place-value strategy.','4.NBT.B.4'],['sub','Subtract bigger numbers','Regroup across places.','4.NBT.B.4'],['angle','A turn of an angle','Relate degrees to familiar turns.','4.MD.C.5']],
[['decimal','Add and subtract decimals','Align equal place values.','5.NBT.B.7'],['decimalmul','Multiply decimals','Use whole-number products and place value.','5.NBT.B.7'],['decimaldiv','Divide decimals','Scale both numbers by the same power of ten.','5.NBT.B.7'],['fracunlike','Unlike denominators','Rename fractions using a common denominator.','5.NF.A.1'],['fracmul','Multiply fractions','Multiply numerators and denominators.','5.NF.B.4'],['volume','Fill a prism','Count layers of unit cubes.','5.MD.C.5'],['powers','Powers of ten','Use repeated multiplication by ten.','5.NBT.A.2'],['mul2','Multi-digit multiplication','Use partial products to check a product.','5.NBT.B.5']],
[['ratio','Ratio recipes','Scale both parts of a ratio equally.','6.RP.A.3'],['percent','Percent means per hundred','Find a percent of a quantity.','6.RP.A.3'],['integer','Integers on a line','Compare numbers on either side of zero.','6.NS.C.7'],['expression','Evaluate an expression','Replace a variable with its value.','6.EE.A.2'],['equation','Find the missing number','Undo an operation to solve an equation.','6.EE.B.7'],['triangle','Area of a triangle','Use half the area of a matching rectangle.','6.G.A.1'],['mean','A fair-share average','Add all values and divide by their count.','6.SP.B.5'],['fracdiv','Divide by a fraction','Count how many fractional groups fit.','6.NS.A.1']]
];
const phonics=[
{title:'Short a: tap and blend',objective:'Connect letters with sounds in simple short-a words.',pattern:'Short a is the vowel sound in cat. Point to each letter, say its sound, then blend without a long pause.',words:['cat','map','sat','tap'],parts:['c · a · t','m · a · p','s · a · t','t · a · p'],contrast:['cat','cot','cut'],answer:0,question:'Which word has the same middle vowel sound as map?',standard:'RF.K.3'},
{title:'Two letters, one sound',objective:'Recognize the sh spelling in familiar words.',pattern:'The letters s and h work together in ship. Keep the sh sound together when you blend the rest of the word.',words:['ship','shop','fish','dish'],parts:['sh · i · p','sh · o · p','f · i · sh','d · i · sh'],contrast:['ship','sip','tip'],answer:0,question:'Which word begins with the sh spelling?',standard:'RF.1.3'},
{title:'Vowel teams: ee and ea',objective:'Recognize common spellings of the long-e sound.',pattern:'In seed and leaf, two letters work together to spell the long-e sound. Some spellings have more than one sound, so listen to the whole word too.',words:['seed','tree','leaf','team'],parts:['s · ee · d','t · r · ee','l · ea · f','t · ea · m'],contrast:['seed','sad','said'],answer:0,question:'Which word has the long-e sound?',standard:'RF.2.3'},
{title:'Unlock a prefix',objective:'Use common prefixes to decode and understand words.',pattern:'A prefix comes before a base word. Un- often means not. Re- often means again. Read the base, then add the prefix.',words:['unfair','replay','unpack','refill'],parts:['un · fair','re · play','un · pack','re · fill'],contrast:['play again','stop playing','play outside'],answer:0,question:'What does replay mean?',standard:'RF.3.3'},
{title:'Read longer words',objective:'Use syllables and familiar word parts to read longer words.',pattern:'Break a long word into manageable parts. Say the parts, blend them, and check that the word makes sense in its sentence.',words:['carefully','disagree','helpfulness','sunflower'],parts:['care · ful · ly','dis · a · gree','help · ful · ness','sun · flow · er'],contrast:['without care','with care','before care'],answer:1,question:'What does carefully mean?',standard:'RF.4.3'},
{title:'Roots help words grow',objective:'Use familiar roots and affixes to understand vocabulary.',pattern:'A root carries meaning. Tele means far. Graph relates to writing. A telescope helps us look far away; a photograph records an image using light.',words:['telescope','photograph','transport','portable'],parts:['tel · e · scope','pho · to · graph','trans · port','port · a · ble'],contrast:['far','small','water'],answer:0,question:'What does tele contribute to telescope?',standard:'RF.5.3'},
{title:'Word parts in context',objective:'Use roots, affixes, and context to infer word meaning.',pattern:'Use more than one clue. Break the word into parts, read the surrounding sentence, and check the meaning against the context.',words:['geography','biography','renewable','prediction'],parts:['ge · og · ra · phy','bi · og · ra · phy','re · new · a · ble','pre · dic · tion'],contrast:['an account of a life','a weather chart','a type of rock'],answer:0,question:'What is a biography?',standard:'L.6.4'}
];
const books=[
{title:'Sam and the Map',tag:'Short-a practice',pages:['Sam has a map. A cat sat on the map.','Sam can tap. Tap, tap, tap! The cat ran.','Sam has the map. The cat can nap.'],question:'What did the cat sit on?',options:['A map','A log','A bed'],answer:0,explanation:'The first page says that the cat sat on the map.',vocab:'map',meaning:'A drawing that helps show where places are.'},
{title:'A Shell for Pip',tag:'Digraphs & story order',pages:['Pip and Ash went to the shore. A small shell lay by a rock.','“Shall we take it?” asked Ash. Then a tiny crab peeked out.','“This shell is a home,” said Pip. They left it on the shore and drew a picture instead.'],question:'Why did Pip leave the shell?',options:['It was too large.','A crab was using it as a home.','Pip forgot it.'],answer:1,explanation:'Pip noticed the crab inside and understood that the shell was its home.',vocab:'shore',meaning:'The land along the edge of water.'},
{title:'The Seed Library',tag:'Vowel teams & cause and effect',pages:['Mina found a small box beside the library desk. A sign said, “Take a seed. Grow something. Share what you learn.”','She planted a bean seed in a cup with drainage holes. She watered the soil and put the cup near a sunny window after the seed sprouted.','Soon, two green leaves opened. Mina drew them in her notebook. She could not return the same seed, but later she could share seeds from a grown plant.'],question:'Why did Mina draw the leaves?',options:['To record what she observed','To make the plant taller','To hide the plant'],answer:0,explanation:'Her notebook helps her record and compare changes over time.',vocab:'sprouted',meaning:'Began to grow from a seed.'},
{title:'The Bridge Builders',tag:'Character & evidence',pages:['After the rain, a shallow stream crossed the trail. Noor wanted to jump, but Pip noticed that the bank was slippery.','They made a model bridge with folded paper and tested it with pebbles. Flat paper bent quickly. A folded strip held more pebbles.','“The folds changed how the load was carried,” Noor said. They took their model to an adult and asked how a real bridge could be designed safely.'],question:'Which detail shows that Noor and Pip tested an idea?',options:['It had rained.','They put pebbles on two paper designs.','They liked the trail.'],answer:1,explanation:'Comparing the two designs with pebbles provided evidence about how much each could hold.',vocab:'load',meaning:'The weight that a structure supports.'},
{title:'Two Accounts of One Day',tag:'Perspective & sources',pages:['A town archive held two accounts of a storm from long ago. In a shopkeeper’s diary, the storm was a disaster: rain had spoiled sacks of flour.','In a farmer’s letter, the same rain was a relief after weeks of dry weather. Both writers described what mattered in their own lives.','A young researcher compared the accounts with a weather record. She learned that different experiences can shape how people describe the same event.'],question:'Why do the accounts describe the storm differently?',options:['One writer must be lying.','The storm affected the writers differently.','Diaries never contain facts.'],answer:1,explanation:'Each writer describes a different effect of the storm. Comparing sources helps build a fuller picture.',vocab:'perspective',meaning:'A point of view shaped by someone’s experience.'},
{title:'The Case of the Warmer Garden',tag:'Evidence & fair tests',pages:['Two garden beds grew the same kind of lettuce. One bed was shaded in the afternoon; the other received sunlight all day. Their soil temperatures differed.','Pip wanted to know whether shade caused the difference. “We should measure at the same time, use the same thermometer, and compare several days,” said Leila.','They also checked watering and soil type. Their results suggested a pattern, but they recorded the limits of their investigation before making a claim.'],question:'Which change makes their comparison fairer?',options:['Use different thermometers each day.','Measure one bed at noon and one at night.','Measure both beds at the same time.'],answer:2,explanation:'Keeping the measurement time the same reduces one possible source of variation.',vocab:'variable',meaning:'A factor that can change in an investigation.'},
{title:'A River Connects Us',tag:'Systems & inference',pages:['A river crossed farms, a town, and a wetland before reaching the sea. People upstream used its water for crops. Downstream, the wetland provided habitat and helped slow floodwater.','During a dry season, a council compared water-use records, rainfall data, and accounts from residents. Each source answered different questions and had its own limits.','The council proposed a trial conservation plan and agreed to review the results. Solving the problem required evidence, cooperation, and attention to people who experienced the river differently.'],question:'Which statement best captures the main idea?',options:['Only upstream communities depend on rivers.','Connected places need shared evidence and cooperation.','One source can answer every question.'],answer:1,explanation:'The passage connects different communities and shows them using several sources to plan together.',vocab:'conservation',meaning:'Careful use and protection of resources.'}
];
// Original, bounded introductory lessons. Science/social studies are topic sequences, not claims of standards coverage.
const knowledge={scienceLab:[
[['Use your senses','Observe properties safely.','We can describe objects by their color, shape, texture, and sound. An observation tells what we notice, not just what we guess. Never taste an unknown object.','Which is an observation?',['The leaf is green.','The leaf is happy.','The leaf is magic.'],0,'Color is a property we can observe.','Find three objects. Describe their color and shape.'],['Push and pull','Explore how forces change motion.','A push moves something away; a pull brings it toward you. A gentle force can start or stop a toy.','You draw a wagon toward you. Is that a push or a pull?',['Push','Pull','Neither'],1,'Bringing the wagon toward you is a pull.','With a grown-up, gently push and pull a toy. What changes?']],
[['What plants need','Connect plant needs to observations.','Green plants need light, water, air, and suitable conditions to grow. Roots take up water and leaves use light to help make food.','Which part takes in water from the soil?',['Flower','Root','Fruit'],1,'Roots absorb water from the soil.','Observe a plant for several days. Draw a change.'],['Light and shadows','Explore what blocks light.','A shadow forms when an opaque object blocks light. Moving a light or object can change the shadow. Never look directly at the Sun.','Why does a book make a shadow?',['It blocks light.','It makes darkness.','It is cold.'],0,'The book blocks some light from reaching the surface behind it.','Use a lamp and your hand. Move your hand and notice the shadow.']],
[['Material detectives','Compare material properties.','A material’s properties help us choose how to use it. A raincoat needs to resist water; a towel needs to absorb water.','Which property is useful for a towel?',['Absorbs water','Lets all water run off','Breaks when wet'],0,'Absorbing water helps a towel dry things.','Compare a paper towel and a spoon with a grown-up. Which absorbs a drop of water?'],['Changing water','Identify changes of state.','Water can be solid ice, liquid water, or water vapor. Warming ice makes it melt. Cooling liquid water enough makes it freeze.','Ice becoming liquid is called…',['freezing','melting','planting'],1,'Melting is the change from solid to liquid.','Watch an ice cube in a bowl. Record what changes.']],
[['Life cycles','Recognize stages in a life cycle.','Many butterflies begin as eggs, hatch as caterpillars, form a pupa, and emerge as adults. Not all animals have this same cycle.','Which stage comes after a caterpillar?',['Pupa','Egg','Adult bird'],0,'The caterpillar forms a pupa before becoming an adult butterfly.','Draw the four stages and connect them with arrows.'],['Fair comparisons','Plan a simple fair comparison.','To compare paper bridge designs, use the same paper size, the same gap, and the same weights. Change only the design you are testing.','What should stay the same?',['The bridge design','The gap between supports','The result'],1,'Keeping the gap the same makes the comparison more useful.','Compare flat and folded paper across the same small gap using coins.']],
[['Energy on the move','Follow energy through a simple system.','A moving ball has energy. When it strikes another ball, it can transfer energy and make the second ball move.','What can happen when a moving ball hits a still ball?',['Energy transfers and the second ball moves.','All energy disappears.','The second ball becomes weightless.'],0,'The interaction can transfer energy between the balls.','Roll a ball gently into another on a clear floor and observe.'],['Weathering and erosion','Distinguish breaking down from moving away.','Weathering breaks rock into smaller pieces. Erosion moves sediment by water, wind, ice, or gravity.','A stream carries sand downstream. This is…',['erosion','evaporation','freezing'],0,'Moving sediment from one place to another is erosion.','Find evidence of moved soil after rain without entering flowing water.']],
[['Food webs','Trace food energy through organisms.','Plants use light to make food. Animals obtain food by eating plants or other animals. Decomposers help return materials to the environment.','Where does much of the energy entering a meadow food web begin?',['The Sun','A rabbit','A fox'],0,'Plants capture energy from sunlight; that food energy can pass to consumers.','Draw a simple path: sunlight, grass, rabbit, fox.'],['Earth and sky','Distinguish rotation from orbit.','Earth rotates roughly once a day and orbits the Sun roughly once a year. As Earth rotates, places face toward and away from the Sun.','What mainly causes day and night?',['Earth’s rotation','The Moon making light','The Sun switching off'],0,'Rotation changes whether your location faces the Sun.','Use a globe or ball and a lamp to model day and night.']],
[['Particles and states','Use a particle model of matter.','Matter is made of particles. In a solid they stay close and vibrate around positions; in a liquid they remain close but move past one another. Gas particles are much farther apart.','Which model best describes a gas?',['Particles far apart and moving','Particles fixed in neat rows','No particles'],0,'A gas has widely spaced particles that move through the available space.','Draw particle models for a solid, liquid, and gas.'],['Ecosystem interactions','Explain how one change can affect a system.','Organisms interact through food, habitat, and competition. A change to one population can affect others, but evidence is needed to predict the result in a real ecosystem.','If insects eaten by birds decrease, what is a reasonable concern?',['The birds may have less food.','The birds no longer need food.','Every bird will immediately disappear.'],0,'Reduced food can affect birds, though actual effects depend on other factors.','Draw a small food web and discuss one possible change.']]],
history:[
[['Before and after','Order familiar events.','A timeline places events in order. Yesterday happened before today. Tomorrow comes after today.','Which happened first?',['Tomorrow','Today','Yesterday'],2,'Yesterday comes before today.','Draw three events from your day in order.'],['Clues from the past','Notice how objects tell stories.','An old photo can show clothing, places, and people from an earlier time. Ask what you can actually see before guessing.','What can a photograph directly show?',['What someone secretly thought','What clothing was visible','Everything that happened that year'],1,'Visible details are evidence; hidden thoughts need other sources.','Ask a grown-up about an old family object.']],
[['Life then and now','Compare change and continuity.','Some people once used handwritten letters where many now use electronic messages. People still communicate, but their tools can change.','What stayed similar?',['People communicate.','All tools are identical.','Nobody writes anymore.'],0,'The purpose can stay similar even when tools change.','Compare an older and newer way of doing the same task.'],['Community stories','Learn from a person’s account.','An oral history records someone’s memories. Memories are valuable, but another person may remember an event differently.','What is a good question for an oral history?',['What was school like when you were young?','What is my favorite color?','Can all memories be identical?'],0,'That question invites a person to describe their experience of the past.','Ask a willing grown-up about one childhood memory.']],
[['Build a timeline','Use dates to order events.','Dates help us put events in order. For years in the Common Era, a smaller positive year number comes earlier.','Which year comes first?',['2005','1998','2012'],1,'1998 is earlier than 2005 and 2012.','Make a timeline of three events you know.'],['Objects as evidence','Ask questions about an artifact.','An artifact is an object made or used by people. Its material, wear, and location may offer clues, but one object rarely tells the whole story.','Which question helps investigate an old tool?',['Who used it and what for?','Was it secretly magic?','Can we assume everyone owned it?'],0,'Purpose and users help explain an artifact’s context.','Sketch an everyday object and label what a future historian might infer.']],
[['Primary and secondary sources','Distinguish direct evidence from later accounts.','A diary written during an event is a primary source. A later textbook describing that event is a secondary source. Both need careful reading.','Which is a primary source for a past school day?',['A diary entry written that day','A modern novel about school','A later summary without sources'],0,'The diary was created at the time and records a person’s account.','Compare a photo with a later description of it.'],['History has perspectives','Compare accounts of the same event.','Two witnesses may notice different details because they stood in different places or had different experiences. Compare accounts and look for additional evidence.','Two accounts disagree. What should you do?',['Choose the longer one automatically','Compare evidence and context','Ignore both forever'],1,'Looking at context and other evidence helps explain differences.','Describe a shared event with a friend, then compare details.']],
[['Trade connects communities','Explain why people exchange goods.','Communities trade for goods they want or need. Trade routes can also carry ideas and technologies. Exchanges can have unequal benefits and costs.','What can move along a trade route besides goods?',['Ideas','Only boxes','Nothing else'],0,'People can exchange knowledge and technologies as well as goods.','Trace where two everyday products were made using their labels.'],['Reading a historical map','Use a map in its time and context.','A historical map reflects knowledge, purposes, and choices from the time it was made. Compare its date, labels, and boundaries with other sources.','What should you check before interpreting an old map?',['Its date and creator','Only its color','Whether it looks new'],0,'Date and creator help establish the map’s context.','Compare two maps from different dates with an adult.']],
[['The US Constitution','Distinguish a framework of government from an event list.','The United States Constitution establishes the federal government’s framework. Its articles describe powers and structures; amendments make changes. The Bill of Rights is the first ten amendments.','What is an amendment?',['A change or addition to the Constitution','A weather report','A type of coin'],0,'Amendments change or add to the constitutional framework.','Identify a classroom rule and explain why a group might revise it.'],['Claims need evidence','Support a historical claim.','A historian connects a claim to evidence, explains the connection, and acknowledges what the sources cannot establish. One source may have gaps.','Which best supports a claim about how a town grew?',['Several dated population records','A guess based on its name','One undated drawing alone'],0,'Dated records allow a comparison over time.','Make a claim about a change in your community and list possible sources.']],
[['Ancient river communities','Connect environment and settlement.','Some early cities grew near rivers that supported farming and transport. Rivers also brought flood risks. Geography influenced choices without determining every outcome.','Why could a river attract settlement?',['Water for farming and transport','It prevented every disaster','It made all communities identical'],0,'Water and transport were useful, though communities still faced risks.','List benefits and challenges of living near a river.'],['Cause and consequence','Look beyond a single cause.','Historical changes often have several causes. Technology, resources, decisions, and environmental conditions can interact. A timeline alone does not prove causation.','Two events happen in order. Does that prove the first caused the second?',['Always','No, more evidence is needed','Only if they happened in summer'],1,'Order is useful, but a causal explanation needs evidence of a connection.','Describe two possible causes of a familiar change.']]],
geography:[
[['A map of my room','Understand a map as a representation.','A map shows a place using a smaller drawing. We can draw a room as if looking down from above.','What does a room map represent?',['A place','A song','A smell'],0,'A map represents where things are in a place.','Draw your room from above and label one object.'],['Land and water','Identify basic features.','Land is solid ground. Lakes, rivers, and oceans contain water. A coastline is where land meets the sea.','Where does a coastline lie?',['Where land meets the sea','Inside every mountain','Only in a city center'],0,'A coastline marks the edge between land and sea.','Look at a globe with an adult and point to land and water.']],
[['Map symbols','Use a key to interpret a map.','A map key explains symbols. A small tree symbol might represent a park, if the key says so. Symbols can differ between maps.','Where do you look to learn what a symbol means?',['The map key','Your shoe','The page number only'],0,'The key connects each symbol to its meaning.','Invent a key with three symbols for your neighborhood.'],['The four directions','Use north, east, south, and west.','On a map with north at the top, east is right, south is down, and west is left. Always check the direction marker.','On a north-up map, which direction is right?',['West','East','South'],1,'East lies to the right when north is up.','Draw a compass rose and label the four directions.']],
[['Continents and oceans','Distinguish major land areas from oceans.','In the seven-continent model, continents are Africa, Antarctica, Asia, Europe, North America, South America, and Australia. Oceans separate and connect places.','Which is a continent?',['Pacific','Asia','Atlantic'],1,'Asia is a continent. Pacific and Atlantic are oceans.','Find your continent on a globe.'],['A bird’s-eye view','Connect a map to a place.','A bird’s-eye view looks down at a place. A map simplifies that view using lines, labels, and symbols.','Which view best helps draw a simple floor plan?',['Looking down from above','Looking only at the ceiling','Looking inside a cupboard'],0,'An overhead view helps show the arrangement of the room.','Sketch a route from a doorway to a desk.']],
[['Map scale','Connect map distance to real distance.','A scale tells how a map distance relates to a real distance. If 1 centimeter represents 2 kilometers, 3 centimeters represents 6 kilometers.','At 2 km per centimeter, what does 4 cm represent?',['2 km','6 km','8 km'],2,'Four groups of 2 kilometers make 8 kilometers.','Create a pretend map with a scale and measure a route.'],['Landforms','Recognize mountains, valleys, and plains.','A mountain rises high above surrounding land. A valley is a lower area between hills or mountains. A plain is a broad, relatively flat area.','What is a lower area between hills or mountains?',['Valley','Peak','Ocean current'],0,'A valley lies between higher areas.','Draw and label a mountain, valley, and plain.']],
[['Latitude and longitude','Use two coordinate directions.','Latitude measures position north or south of the Equator. Longitude measures position east or west of the Prime Meridian. Together they help locate a place.','Which measures north or south of the Equator?',['Longitude','Latitude','Altitude'],1,'Latitude measures north-south position; altitude measures height.','Find the Equator and Prime Meridian on a globe.'],['Weather or climate?','Distinguish short-term conditions from long-term patterns.','Weather describes conditions at a particular time. Climate describes long-term patterns, usually studied across many years. One hot day does not establish a climate trend.','Which describes weather?',['It is raining this afternoon.','A region usually has dry summers.','Long-term average rainfall'],0,'This afternoon describes a short-term condition.','Record today’s weather, then compare it with a description of local climate.']],
[['People and resources','Connect resources, use, and choices.','Resources include water, soil, minerals, and energy sources. Their use can benefit communities and affect environments. Decisions involve tradeoffs.','What is a tradeoff when using river water for irrigation?',['More water for crops may leave less downstream.','Water becomes unlimited.','There can be no effect elsewhere.'],0,'Using a shared resource in one place can affect another.','Trace one resource you use and discuss how to conserve it.'],['Maps make choices','Notice projection and purpose.','A flat map represents a curved Earth. Every world-map projection distorts some combination of area, shape, distance, or direction. Choose a map for its purpose.','Can one flat world map preserve all properties perfectly?',['Yes','No','Only if it has bright colors'],1,'Flattening a curved surface requires some distortion.','Compare a globe with a world map. Notice high-latitude shapes.']],
[['Population and place','Distinguish total population from density.','Population density compares people with land area. A place with a larger population does not always have a higher density if its area is much larger.','Two towns each have 1,000 people. Which is denser?',['The town covering 2 square km','The town covering 10 square km','They must be equally dense'],0,'The same population in less area produces higher density.','Calculate a pretend town’s people per square kilometer.'],['Connected systems','Trace a geographic connection.','Food, water, transport, and trade connect places. An event in one location can affect people elsewhere. Maps and data help us trace these connections.','A major shipping route closes. What is a possible effect?',['Some deliveries take longer.','All geography stops mattering.','Every product disappears forever.'],0,'Goods may need a longer route, though effects vary.','Choose an item and trace the places involved in making and moving it.']]]};
const lessons=[];
mathSpecs.forEach((list,grade)=>list.forEach((s,i)=>lessons.push({id:`m-${grade}-${i}`,subject:'maths',grade,kind:'math',mode:s[0],title:s[1],objective:s[2],standard:s[3],minutes:8,order:i})));
phonics.forEach((p,grade)=>{lessons.push({id:`r-${grade}-0`,subject:'reading',grade,kind:'phonics',title:p.title,objective:p.objective,standard:p.standard,minutes:8,order:0,phonics:p});lessons.push({id:`r-${grade}-1`,subject:'reading',grade,kind:'book',title:books[grade].title,objective:'Read connected text, explore vocabulary, and support an answer with the text.',standard:grade===0?'RL.K.1':`RL.${grade}.1`,minutes:10,order:1,book:books[grade]});});
Object.entries(knowledge).forEach(([subject,grades])=>grades.forEach((rows,grade)=>rows.forEach((r,i)=>lessons.push({id:`${subject}-${grade}-${i}`,subject,grade,kind:'inquiry',title:r[0],objective:r[1],teach:r[2],question:r[3],options:r[4],answer:r[5],explanation:r[6],activity:r[7],minutes:8,order:i,standard:null}))));
function gcd(a,b){return b?gcd(b,a%b):Math.abs(a);}
function rational(n,d){let g=gcd(n,d);return d/g===1?String(n/g):`${n/g}/${d/g}`;}
function numeric(input){const s=String(input).trim();if(/^[-+]?\d+\s*\/\s*[-+]?\d+$/.test(s)){const[n,d]=s.split('/').map(Number);return d===0?NaN:n/d;}return /^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)?Number(s):NaN;}
function accepted(input,answer){return typeof answer==='number'?Number.isFinite(numeric(input))&&Math.abs(numeric(input)-answer)<1e-8:String(input).trim().toLowerCase()===String(answer).toLowerCase();}
function addSteps(a,b){let carry=0;const labels=['ones','tens','hundreds','thousands','ten-thousands'];let steps=[];const len=Math.max(String(a).length,String(b).length);for(let i=0;i<len;i++){let x=Math.floor(a/10**i)%10,y=Math.floor(b/10**i)%10,total=x+y+carry;steps.push(`${labels[i]}: ${x} + ${y}${carry?' + 1 carried':''} = ${total}. ${total>=10?`Write ${total%10} in the ${labels[i]} column and regroup 10 ${labels[i]} as 1 in the next column.`:`Write ${total} in the ${labels[i]} column.`}`);carry=Math.floor(total/10);}if(carry)steps.push('Place the remaining carried 1 in the next column.');steps.push(`Put the place values together: ${a} + ${b} = ${a+b}.`);return steps;}
function subSteps(a,b){const digits=String(a).split('').reverse().map(Number),labels=['ones','tens','hundreds','thousands','ten-thousands'];let steps=[];for(let i=0;i<digits.length;i++){let y=Math.floor(b/10**i)%10;if(digits[i]<y){let k=i+1;while(digits[k]===0)k++;digits[k]--;for(let j=k-1;j>i;j--)digits[j]=9;digits[i]+=10;steps.push(`Regroup from the ${labels[k]} place through to the ${labels[i]} place. Now there are ${digits[i]} ${labels[i]} available.`);}steps.push(`${labels[i]}: ${digits[i]} − ${y} = ${digits[i]-y}.`);}steps.push(`Check by adding: ${a-b} + ${b} = ${a}.`);return steps;}
function problem(lesson,seed=0){const g=lesson.grade,m=lesson.mode,s=Math.abs(seed)%10000,k=s%5;let a,b,answer,prompt,steps=[],visual=null,options=null,display;
if(['add','add2','add3'].includes(m)){if(m==='add'){a=g===0?2+k:8+k;b=g===0?1+k%3:3+k;}else if(m==='add2'){[a,b]=[[56,34],[47,28],[68,17],[35,46],[79,15]][k];if(g===1){a=21+k*10;b=12+k;}}else{[a,b]=[[246,134],[358,267],[487,156],[629,284],[705,186]][k];if(g>=4){a+=2300;b+=1400;}}if(s>=5){a+=s%7;if(g===0)a=Math.min(a,10-b);if(g===1&&m==='add')a=Math.min(a,20-b);}answer=a+b;prompt=`${a} + ${b}`;steps=addSteps(a,b);visual={type:g===0?'counters':'columns',a,b,op:'+'};}
else if(m==='sub'){if(g===0){a=5+k;b=1+k%3;}else if(g===1){a=12+k;b=3+k%3;}else{[a,b]=[[352,178],[403,168],[624,257],[510,236],[801,457]][k];if(g>=4){a+=2000;b+=1000;}}answer=a-b;prompt=`${a} − ${b}`;steps=subSteps(a,b);visual={type:g===0?'counters':'columns',a,b,op:'−'};}
else if(['mul','mul2','array','div','remainder'].includes(m)){a=m==='mul2'?23+k*7:g>=4?24+k*8:3+k;b=m==='mul2'?12+k:2+k;const total=a*b;if(m==='div'){answer=a;prompt=`${total} ÷ ${b}`;steps=[`Share ${total} into ${b} equal groups.`,`Use the related multiplication fact: ${b} × ${a} = ${total}.`,`Each group has ${a}. Check: ${a} × ${b} = ${total}.`];visual={type:'groups',a:Math.min(a,12),b,caption:`${b} groups with ${a} in each; total ${total}.${a>12?' The model shows only part of each group.':''}`};}else if(m==='remainder'){const r=1+k%(b-1);answer=r;prompt=`${total+r} ÷ ${b}: what is the remainder?`;steps=[`${b} × ${a} = ${total}.`,`${total+r} − ${total} = ${r}.`,`${r} is smaller than the divisor ${b}. The quotient is ${a}, with remainder ${r}.`];}else{answer=total;prompt=m==='array'?`${a} rows with ${b} counters in each. How many counters?`:`${a} × ${b}`;steps=m==='mul2'?[`Break ${b} into ${Math.floor(b/10)*10} + ${b%10}.`,`${a} × ${Math.floor(b/10)*10} = ${a*Math.floor(b/10)*10}.`,`${a} × ${b%10} = ${a*(b%10)}.`,`Add the partial products: ${a*Math.floor(b/10)*10} + ${a*(b%10)} = ${total}.`]:[`${a} groups of ${b} means add ${b}, ${a} times.`,`${Array(a).fill(b).join(' + ')} = ${total}.`,`So ${a} × ${b} = ${total}.`];visual={type:'array',a:Math.min(a,10),b:Math.min(b,10),caption:a>10?'A smaller array illustrates the equal-row structure.':`${a} equal rows of ${b}`};}}
else if(m==='count'){answer=3+k;prompt='How many counters can you count?';steps=[`Touch each counter once as you count.`,`The last number you say is the total: ${answer}.`];visual={type:'dots',n:answer};}
else if(m==='ten'){a=2+k;answer=10-a;prompt=`${a} + ? = 10`;steps=[`Start with ${a}.`,`Count on from ${a} to 10. You need ${answer} more.`,`${a} + ${answer} = 10.`];visual={type:'ten',n:a};}
else if(m==='compare'||m==='integer'){a=m==='integer'?-2-k:g===0?3+k:24+k*10;b=m==='integer'?1-k:g===0?8-k:32+k*7;answer=a>b?'>':a<b?'<':'=';options=['<','=','>'];prompt=`Choose the symbol: ${a} ? ${b}`;steps=[m==='integer'?'On a number line, numbers farther right are greater.':'Compare the highest place value first, then the next.',`${a} is ${answer==='>'?'greater than':answer==='<'?'less than':'equal to'} ${b}.`,`Use ${answer}.`];}
else if(m==='shape'){const data=[['triangle',3],['square',4],['hexagon',6],['pentagon',5],['octagon',8]][k];answer=data[1];prompt=`How many sides does a ${data[0]} have?`;steps=[`Trace the outside edge of a ${data[0]}.`,`Count each straight side once: ${data[1]} sides.`];visual={type:'polygon',sides:data[1]};}
else if(m==='place'){a=g===1?43+k*10:246+k*101;let power=g===1?10:100;answer=Math.floor(a/power)%10*power;prompt=`What is the value of the digit ${Math.floor(a/power)%10} in ${a}?`;steps=[`The digit is in the ${power===10?'tens':'hundreds'} place.`,`${Math.floor(a/power)%10} × ${power} = ${answer}.`,`The digit’s value is ${answer}, not just the digit by itself.`];}
else if(m==='clock'){a=2+k;answer=0;prompt=`At exactly ${a} o’clock, how many minutes past the hour is it?`;steps=[`O’clock means the minute hand is at 12.`,`It is ${a}:00, so 0 minutes have passed since ${a}.`];}
else if(m==='money'){a=2+k;b=1+k;answer=a*10+b*5;prompt=`${a} US dimes and ${b} US nickels: how many cents?`;steps=[`Each dime is 10 cents: ${a} × 10 = ${a*10}.`,`Each nickel is 5 cents: ${b} × 5 = ${b*5}.`,`Add the values: ${a*10} + ${b*5} = ${answer} cents.`];}
else if(m==='length'){a=18+k*3;b=7+k;answer=a-b;prompt=`One ribbon is ${a} cm long. Another is ${b} cm. How many centimeters longer is the first?`;steps=[`Both lengths use centimeters, so subtract.`,`${a} − ${b} = ${answer} cm.`];}
else if(['fraction','equiv','fracadd','fracunlike','fracmul','fracdiv'].includes(m)){a=1+k%3;b=4+k%3;if(m==='fraction'){answer=a/b;display=`${a}/${b}`;prompt=`${a} of ${b} equal parts are shaded. What fraction is shaded?`;steps=[`The denominator counts all ${b} equal parts.`,`The numerator counts the ${a} shaded parts.`,`The fraction is ${a}/${b}.`];visual={type:'fraction',a,b};}else if(m==='equiv'){answer=a*2;prompt=`${a}/${b} = ?/${b*2}. What is the missing numerator?`;steps=[`The denominator was multiplied by 2.`,`Multiply the numerator by the same amount: ${a} × 2 = ${answer}.`,`Both fractions name the same amount.`];}else if(m==='fracadd'){answer=(a+1)/b;display=rational(a+1,b);prompt=`${a}/${b} + 1/${b}`;steps=[`The parts have the same size: ${b}ths.`,`Add the numerators: ${a} + 1 = ${a+1}.`,`Keep the denominator: ${a+1}/${b} = ${display}.`];}else if(m==='fracunlike'){answer=1/2+1/(4+2*k);display=rational(3+k,4+2*k);prompt=`1/2 + 1/${4+2*k}`;steps=[`Use the common denominator ${4+2*k}.`,`1/2 = ${2+k}/${4+2*k}.`,`Add: ${2+k}/${4+2*k} + 1/${4+2*k} = ${3+k}/${4+2*k} = ${display}.`];}else if(m==='fracmul'){answer=a/b*2/3;display=rational(a*2,b*3);prompt=`${a}/${b} × 2/3`;steps=[`Multiply numerators: ${a} × 2 = ${a*2}.`,`Multiply denominators: ${b} × 3 = ${b*3}.`,`Simplify ${a*2}/${b*3} to ${display}.`];}else{answer=a*b;prompt=`${a} ÷ 1/${b}`;steps=[`How many pieces of size 1/${b} fit in ${a}?`,`There are ${b} pieces in each whole.`,`${a} × ${b} = ${answer} pieces.`];}}
else if(['area','perimeter','volume','triangle'].includes(m)){a=4+k;b=3+k;answer=m==='area'?a*b:m==='perimeter'?2*(a+b):m==='volume'?a*b*2:a*b/2;prompt=m==='area'?`A rectangle is ${a} cm by ${b} cm. What is its area in square cm?`:m==='perimeter'?`A rectangle is ${a} cm by ${b} cm. What is its perimeter in cm?`:m==='volume'?`A prism is ${a} cm long, ${b} cm wide, and 2 cm high. What is its volume in cubic cm?`:`A triangle has base ${a} cm and perpendicular height ${b} cm. What is its area in square cm?`;steps=m==='area'?[`Area counts the squares that cover a surface.`,`${a} rows of ${b} squares = ${a*b} square cm.`]:m==='perimeter'?[`Perimeter measures around the outside.`,`${a} + ${b} + ${a} + ${b} = ${answer} cm.`]:m==='volume'?[`One layer holds ${a} × ${b} = ${a*b} cubes.`,`Two layers hold ${a*b} × 2 = ${answer} cubic cm.`]:[`A matching rectangle has area ${a} × ${b} = ${a*b}.`,`A triangle takes half that area: ${a*b} ÷ 2 = ${answer} square cm.`];visual={type:'grid',a,b};}
else if(m==='elapsed'){a=15+k*5;b=20+k*3;answer=a+b;prompt=`You read for ${a} minutes and walk for ${b} minutes. How many minutes altogether?`;steps=[`Add the two time intervals.`,`${a} + ${b} = ${answer} minutes.`];}
else if(m==='angle'){const pair=[[90,'quarter'],[180,'half'],[360,'full'],[90,'quarter'],[180,'half']][k];answer=pair[0];prompt=`How many degrees are in a ${pair[1]} turn?`;steps=[`One full turn is 360 degrees.`,`A ${pair[1]} turn is ${answer} degrees.`];}
else if(['decimal','decimalmul','decimaldiv'].includes(m)){a=12+k;b=3+k;if(m==='decimal'){answer=(a*10+b*10+7)/100;prompt=`${(a/10).toFixed(2)} + ${(b/10+.07).toFixed(2)}`;steps=[`Line up the decimal points so equal place values align.`,`In hundredths, add ${a*10} + ${b*10+7} = ${a*10+b*10+7}.`,`Convert back to a decimal: ${answer.toFixed(2)}.`];}else if(m==='decimalmul'){answer=a*b/100;prompt=`${(a/10).toFixed(1)} × ${(b/10).toFixed(1)}`;steps=[`Multiply whole numbers: ${a} × ${b} = ${a*b}.`,`Each factor was divided by 10, so divide the product by 100.`,`The answer is ${answer}.`];}else{answer=a;prompt=`${(a*b/10).toFixed(1)} ÷ ${(b/10).toFixed(1)}`;steps=[`Multiply both dividend and divisor by 10.`,`This gives ${a*b} ÷ ${b}.`,`The quotient is ${a}.`];}}
else if(m==='powers'){a=2+k%3;answer=10**a;prompt=`What is 10 to the power of ${a}?`;steps=[`The exponent counts how many factors of 10 to multiply.`,`${Array(a).fill(10).join(' × ')} = ${answer}.`];}
else if(m==='ratio'){a=2+k;b=3+k;answer=b*3;prompt=`A recipe uses ${a} cups of oats for ${b} cups of fruit. With ${a*3} cups of oats, how many cups of fruit keep the same ratio?`;steps=[`Oats were multiplied by 3: ${a} × 3 = ${a*3}.`,`Multiply fruit by the same factor: ${b} × 3 = ${answer}.`];}
else if(m==='percent'){a=[10,25,50,20,75][k];b=80;answer=a/100*b;prompt=`What is ${a}% of ${b}?`;steps=[`Percent means out of 100, so ${a}% = ${a}/100.`,`Multiply ${b} by ${a}/100 to get ${answer}.`];}
else if(m==='expression'){a=3+k;b=4+k;answer=3*a+b;prompt=`Evaluate 3x + ${b} when x = ${a}.`;steps=[`Replace x with ${a}: 3 × ${a} + ${b}.`,`Multiply first: ${3*a} + ${b}.`,`Add to get ${answer}.`];}
else if(m==='equation'){a=4+k;b=9+k*2;answer=b-a;prompt=`Solve x + ${a} = ${b}. What is x?`;steps=[`Subtract ${a} from both sides.`,`x = ${b} − ${a} = ${answer}.`,`Check: ${answer} + ${a} = ${b}.`];}
else if(m==='mean'){a=4+k;b=8+k;answer=(a+b+6+k)/3;prompt=`Find the mean of ${a}, ${6+k}, and ${b}.`;steps=[`Add the three values: ${a} + ${6+k} + ${b} = ${a+6+k+b}.`,`Divide the total by 3: ${a+6+k+b} ÷ 3 = ${answer}.`];}
else throw new Error('Unknown math mode '+m);
return{prompt,answer,display:display||String(answer),steps,visual,options,a,b,mode:m};}
function feedback(p,input){if(accepted(input,p.answer))return{correct:true,text:'You worked it out! Let’s explain why it works.'};const value=numeric(input);let text='Let’s slow down and use a strategy. A mistake gives us something to investigate.';if(['add','add2','add3'].includes(p.mode)){if(value===p.answer-10||value===p.answer-100)text='One possibility: a regrouped ten or hundred did not make it into the next column. Let’s check each place together.';else text='Line up ones with ones and tens with tens. Start with the ones, and check whether they make a new ten.';}else if(p.mode==='sub')text='Check whether the top digit is smaller in any column. You may need to trade one from the next place for ten here.';else if(['mul','mul2','array'].includes(p.mode)&&value===p.a+p.b)text='You added the two numbers. Multiplication asks for equal groups: count every item in every group.';else if(p.mode.includes('frac'))text='Check the size of the fractional pieces first. Use the worked steps to decide whether to rename, add, multiply, or count groups.';return{correct:false,text};}
function matchReading(expected,heard){const tokenize=s=>s.toLowerCase().replace(/[’']/g,'').match(/[a-z]+/g)||[];const a=tokenize(expected),b=tokenize(heard);const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)dp[i][0]=i;for(let j=0;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));let i=a.length,j=b.length,missed=[];while(i||j){if(i&&j&&a[i-1]===b[j-1]){i--;j--;}else if(i&&j&&dp[i][j]===dp[i-1][j-1]+1){missed.unshift(a[i-1]);i--;j--;}else if(i&&dp[i][j]===dp[i-1][j]+1){missed.unshift(a[i-1]);i--;}else j--;}return{matched:dp[a.length][b.length]===0,missed:[...new Set(missed)],expected:a,heard:b};}
root.WonderCurriculum={subjects,lessons,books,phonics,problem,feedback,accepted,matchReading,numeric,addSteps,subSteps};
if(typeof module!=='undefined')module.exports=root.WonderCurriculum;
})(typeof globalThis!=='undefined'?globalThis:this);
