(function(root){
'use strict';
const C=root.WonderCurriculum;
const specs=[
[['next','Keep counting','Count forward from a number other than one.','K.CC.A.2'],['compose','Build small numbers','Find two parts that make a whole.','K.OA.A.3']],
[['missing','The missing addend','Use subtraction or counting on to find a missing part.','1.OA.D.8'],['double','Double it, then one more','Use a known double to add near doubles.','1.OA.C.6']],
[['change','At the class shop','Subtract a price from the money paid.','2.MD.C.8'],['two','Two changes in one story','Represent two steps with addition and subtraction.','2.OA.A.1']],
[['round','Round to the nearest ten','Compare the distance to neighboring tens.','3.NBT.A.1'],['unit','Compare unit fractions','Compare equal shares of the same whole.','3.NF.A.3d']],
[['factor','Find a factor partner','Use division to complete a factor pair.','4.OA.B.4'],['multiple','Follow the multiples','Use equal jumps to find multiples.','4.OA.B.4']],
[['metric','Meters and centimeters','Convert larger metric units to smaller units.','5.MD.A.1'],['coordinate','Read an ordered pair','Read the horizontal coordinate before the vertical coordinate.','5.G.A.1']],
[['median','The middle of the data','Order data and locate its middle value.','6.SP.B.5c'],['gcf','Greatest common factor','Find the largest factor shared by two numbers.','6.NS.B.4']]
];
specs.forEach((rows,grade)=>rows.forEach(([extensionMode,title,objective,standard],i)=>C.lessons.push({id:`extra-m-${grade}-${i}`,grade,subject:'maths',kind:'math',extensionMode,title,objective,standard,minutes:10,order:100+i})));
const prior=C.problem;
C.problem=function(l,seed=0){if(!l.extensionMode)return prior(l,seed);const k=((Math.floor(seed)%5)+5)%5;let answer,prompt,steps,options,visual;const mode=l.extensionMode;
switch(mode){
case'next':{const a=7+k*2;answer=a+3;prompt=`Keep counting: ${a}, ${a+1}, ${a+2}, __`;steps=[`Begin with ${a}. Each next number is one more.`,`After ${a+2} comes ${answer}.`];break;}
case'compose':{const a=5+k,b=2+k%2;answer=a-b;prompt=`${a} counters are in a bag. ${b} are red. How many are blue?`;steps=[`The whole is ${a}. One part is ${b}.`,`Count on from ${b} to ${a}, or subtract: ${a} − ${b} = ${answer}.`,`Check: ${b} + ${answer} = ${a}.`];visual={type:'dots',n:a};break;}
case'missing':{const a=4+k,b=11+k*2;answer=b-a;prompt=`${a} + __ = ${b}`;steps=[`The whole is ${b}, and one part is ${a}.`,`Find the other part: ${b} − ${a} = ${answer}.`,`Check: ${a} + ${answer} = ${b}.`];break;}
case'double':{const a=3+k;answer=a*2+1;prompt=`${a} + ${a+1}`;steps=[`Use the double: ${a} + ${a} = ${a*2}.`,`The second number is one more, so add one more: ${answer}.`];visual={type:'counters',a,b:a+1,op:'+'};break;}
case'change':{const a=100,b=35+k*5;answer=a-b;prompt=`A notebook costs ${b} cents. You pay 100 cents. How many cents come back?`;steps=[`Change is the amount paid minus the price.`,`100 − ${b} = ${answer} cents.`,`Check: ${b} + ${answer} = 100.`];break;}
case'two':{const a=24+k*3,b=12+k,c=7+k;answer=a+b-c;prompt=`There are ${a} library books. ${b} more arrive. Then ${c} are borrowed. How many remain?`;steps=[`First add the arriving books: ${a} + ${b} = ${a+b}.`,`Then subtract the borrowed books: ${a+b} − ${c} = ${answer}.`];break;}
case'round':{const a=[43,67,85,92,138][k],low=Math.floor(a/10)*10;answer=Math.round(a/10)*10;prompt=`Round ${a} to the nearest ten.`;steps=[`The neighboring tens are ${low} and ${low+10}.`,`The distances are ${a-low} and ${low+10-a}.`,a-low===5?`This is halfway between the tens, so round up to ${answer}.`:`${a} is closer to ${answer}, so the rounded number is ${answer}.`];break;}
case'unit':{const a=k+2,b=k+4;answer=`1/${a}`;prompt=`Which is greater: 1/${a} or 1/${b}, using the same-sized whole?`;options=[`1/${b}`,`1/${a}`];steps=[`Both fractions name one equal part.`,`Dividing the same whole into fewer equal parts makes each part larger.`,`So 1/${a} is greater than 1/${b}.`];break;}
case'factor':{const a=k+3,b=k+4;answer=b;prompt=`Complete a factor pair of ${a*b}: ${a} × __ = ${a*b}`;steps=[`A factor pair multiplies to the whole number.`,`Divide ${a*b} by ${a} to find ${b}.`,`Check: ${a} × ${b} = ${a*b}.`];break;}
case'multiple':{const a=k+3;answer=a*4;prompt=`Continue the multiples of ${a}: ${a}, ${a*2}, ${a*3}, __`;steps=[`Each multiple is one more group of ${a}.`,`Add ${a} to ${a*3}: ${answer}.`,`This is 4 × ${a}.`];break;}
case'metric':{const a=[1.5,2.25,3.4,.75,4.08][k];answer=Math.round(a*100);prompt=`Convert ${a} meters to centimeters.`;steps=[`One meter contains 100 centimeters.`,`Multiply by 100: ${a} × 100 = ${answer}.`,`The length stays the same; the number of smaller units increases.`];break;}
case'coordinate':{const x=k+2,y=8-k;answer=x;prompt=`A point is at (${x}, ${y}). What is its x-coordinate?`;steps=[`An ordered pair is written (x, y).`,`The first number tells the horizontal position: ${x}.`,`From the origin, move ${x} units right and ${y} units up.`];break;}
case'median':{const a=[9+k,3+k,12+k,5+k,7+k],sorted=[...a].sort((a,b)=>a-b);answer=sorted[2];prompt=`Find the median: ${a.join(', ')}.`;steps=[`Order the data: ${sorted.join(', ')}.`,`There are five values, so the third value is the middle.`,`The median is ${answer}. Two values lie on either side.`];break;}
case'gcf':{const a=[12,18,20,24,30][k],b=[18,24,30,36,45][k],f=n=>Array.from({length:n},(_,i)=>i+1).filter(x=>n%x===0),common=f(a).filter(x=>b%x===0);answer=common.at(-1);prompt=`Find the greatest common factor of ${a} and ${b}.`;steps=[`Factors of ${a}: ${f(a).join(', ')}.`,`Factors of ${b}: ${f(b).join(', ')}.`,`Shared factors: ${common.join(', ')}. The greatest is ${answer}.`];break;}
}return{prompt,answer,display:String(answer),steps,options,visual,mode};};
const wordRows=[
[['Short i in little words','Short i is the vowel sound in sit. Say each sound, then blend the sounds together.','sit|pin|lip|wig','s · i · t|p · i · n|l · i · p|w · i · g','Which word has the middle sound in pin?','sit|sun|sat'],['Hear the ending','Listen to the last sound in a word. In map, the final sound is spelled p.','map|cap|tap|nap','m · a · p|c · a · p|t · a · p|n · a · p','Which word ends with the sound spelled p?','tap|tan|tag']],
[['Silent e changes a vowel','Compare cap and cape. In cape, final e helps a say its name. Listen to the whole word.','cape|tape|name|game','c · a_e · p|t · a_e · p|n · a_e · m|g · a_e · m','Which word has long a?','cape|cap|cat'],['Keep the blend','In stop, both s and t keep their sounds. Blend them smoothly into the rest of the word.','stop|step|spin|spot','s · t · o · p|s · t · e · p|s · p · i · n|s · p · o · t','Which word starts with the blend st?','step|ship|sip']],
[['The three sounds of ed','An ed ending can sound like t in jumped, d in played, or an extra syllable in wanted. Read the base and listen to the ending.','jumped|played|wanted|needed','jump · ed|play · ed|want · ed|need · ed','Which word has an extra syllable when ed is added?','wanted|jumped|played'],['Two words become one','A compound word joins two words. The meanings of the parts often help explain the whole.','raincoat|sunlight|bedtime|sandbox','rain · coat|sun · light|bed · time|sand · box','Which word means a coat worn in rain?','raincoat|sunlight|sandbox']],
[['Suffixes tell more','The suffix less often means without. The suffix ful often means full of or having. Read the base before adding the ending.','fearless|hopeful|careless|thankful','fear · less|hope · ful|care · less|thank · ful','What does fearless mean?','without fear|full of fear|before fear'],['Read a contraction','An apostrophe can mark missing letters. Expand a contraction to check its meaning in a sentence.','cannot|can’t|doesn’t|we’re','can · not|can · ’t|does · n’t|we · ’re','What does we’re stand for?','we are|we were|we will']],
[['Words with tion','The ending tion often sounds like shun. Recognize the ending, then work through the rest of the word.','action|motion|invention|collection','ac · tion|mo · tion|in · ven · tion|col · lec · tion','Which word names something newly created?','invention|motion|action'],['A prefix changes direction','Mis- often means wrongly, while pre- means before. Check the full sentence to choose the intended meaning.','misread|preview|misplace|preheat','mis · read|pre · view|mis · place|pre · heat','What does preview mean?','view beforehand|view incorrectly|never view']],
[['Roots for measuring','The word part meter relates to measuring. A thermometer measures temperature; a centimeter is a unit of length.','thermometer|centimeter|kilometer|barometer','ther · mom · e · ter|cen · ti · me · ter|kil · o · me · ter|ba · rom · e · ter','Which word names an instrument for measuring temperature?','thermometer|kilometer|centimeter'],['Related words, changing sounds','Words can share a meaningful base even when pronunciation changes. Compare define and definition, and keep both meaning and sound in mind.','define|definition|sign|signature','de · fine|def · i · ni · tion|sign|sig · na · ture','Which pair shares a meaningful base?','define and definition|define and dolphin|sign and sand']],
[['Precise academic vocabulary','Use roots and context together. Chron relates to time. A chronological account puts events in time order.','chronology|chronological|synchronize|anachronism','chro · nol · o · gy|chron · o · log · i · cal|syn · chro · nize|a · nach · ro · nism','What does chronological order mean?','time order|alphabetical order|order by size'],['A word can have two jobs','Context helps determine meaning and pronunciation. In a record of events, record is a noun. In record your observations, it is a verb. Listen for the changing stress.','a record|record your observations|a present|present your work','a rec · ord|re · cord your ob · ser · va · tions|a pres · ent|pre · sent your work','In “Please record your observations,” what is record doing?','naming an action|naming a stored account|naming a color']]
];
wordRows.forEach((rows,grade)=>rows.forEach(([title,pattern,words,parts,question,contrast],i)=>{const phonics={title,objective:pattern.split('. ')[0]+'.',pattern,words:words.split('|'),parts:parts.split('|'),question,contrast:contrast.split('|'),answer:0,standard:grade===6?'L.6.4':`RF.${grade||'K'}.3`};C.lessons.push({id:`extra-r-${grade}-${i}`,grade,subject:'reading',kind:'phonics',title,objective:phonics.objective,phonics,standard:phonics.standard,minutes:8,order:100+i});}));
// Each lesson includes a taught idea, an evidence question, and a hands-on follow-up.
const inquiry={
scienceLab:[
[['Push it gently','A push can start an object moving. A gentle push and a stronger push may move the same toy different distances. Keep the floor and toy the same when you compare. Watch where the toy stops; do not guess from how hard the push felt.','What should stay the same when comparing two pushes?','the toy and floor|the stopping place|how far it must move','Keeping the toy and floor the same makes the comparison more useful.','With a grown-up, gently push a toy car across a clear floor twice. Mark each stopping place.'],['Watch a shadow','A shadow appears when an object blocks light. Move a toy between a lamp and a wall, and watch its shadow. The shape or size may change as the toy moves. Never look at the sun or touch a hot lamp.','What makes a shadow?','an object blocking light|an object making wind|a sound becoming quiet','A shadow is a region where an object blocks light.','With a grown-up and a cool flashlight, make a hand shadow and describe its outline.']],
[['Animal coverings','Feathers, fur, and scales are different body coverings. Coverings can help animals in different ways, such as keeping warm or protecting their bodies. Compare pictures carefully. A bird and a cat may both live near people, but their coverings are different.','Which observation compares body coverings?','a bird has feathers and a cat has fur|both animals are friendly|one picture is bigger','Feathers and fur describe visible body coverings.','Draw two animals from books and label their coverings.'],['Light through materials','Some materials let much light through. Others let only some light through or block it. A clear window and thick cardboard behave differently. We can compare materials using the same flashlight. Our observations help us choose a material for a window or shade.','Which material would usually work best for seeing through a window?','clear glass|thick cardboard|wood','Clear glass allows light through with a view of objects beyond it.','Ask a grown-up to shine a flashlight through paper and clear plastic. Compare without pointing light at eyes.']],
[['A useful material','A paper towel can absorb spilled water. A smooth plastic tray can hold water without quickly soaking it up. A material is useful when its properties match a job. Test a small amount of water on samples before deciding which would help dry a table.','Which property helps a towel dry a spill?','absorbing water|being shiny|making a loud sound','An absorbent material takes in water from the spill.','With adult help, compare a paper towel and a plastic lid using a few drops of water.'],['A seed travels','Seeds can reach new places in several ways. Wind carries some light seeds; water carries others. Some seeds attach to animal fur. Shape can provide a clue, but a single picture does not prove exactly how a seed traveled. Observations help test the idea.','Which feature could help a seed catch on fur?','small hooks|a printed label|a square box','Hooks can attach to fur and move with an animal.','Sketch a seed from a book. Explain one possible way it might travel and what evidence you used.']],
[['Balanced pushes','Two pushes in opposite directions can balance. When a book rests on a table, gravity pulls downward and the table supports it upward. An object that stays still can still have forces acting on it. Motion alone does not tell us that no forces exist.','Why can a book remain still on a table?','the supporting force balances its weight|gravity disappears indoors|still objects have no forces','The table supports the book while gravity pulls downward.','Draw a resting book with arrows for downward weight and upward support.'],['Weather patterns','Weather changes from day to day. A table of daily observations helps reveal patterns that one afternoon cannot show. Record temperature at a similar time and place. A warm week does not by itself describe a region’s climate, which involves patterns over much longer periods.','Which evidence best describes this week’s temperature pattern?','daily readings taken in a consistent way|one sunny photograph|a guess about next year','Consistent daily readings allow comparisons across the week.','Use a grown-up’s weather source to make a five-day temperature chart.']],
[['Sound needs vibration','A gently plucked rubber band moves back and forth and produces sound. This motion is vibration. Vibrations can travel through materials to our ears. Changing how a band is stretched may change its pitch. Use a secure setup and keep bands away from faces.','What produces the sound of a plucked rubber band?','the band vibrating|its color changing|light passing through it','The back-and-forth motion produces vibrations that can travel to our ears.','With adult help, observe a gently plucked band secured around a small empty box.'],['Erosion and protection','Moving water can carry loose soil away. Plant roots can help hold soil in place, and surface cover can reduce the impact of falling drops. To investigate, compare similar trays with the same slope and amount of water. Change the surface covering rather than several conditions together.','What makes the tray comparison more useful?','keeping slope and water amount the same|using different slopes and water amounts|choosing a winner first','Holding other conditions steady helps connect differences to the surface covering.','Sketch a fair test with two trays. Ask a grown-up before handling soil or water.']],
[['Matter in a closed bag','When ice melts in a closed container, it becomes liquid water. The material has changed state. If nothing enters or leaves, its total mass is conserved. A puddle disappearing from an open tray does not mean matter stopped existing; water can enter the air as vapor.','Why use a closed container when comparing mass before and after melting?','to prevent matter entering or leaving|to make gravity stronger|to stop time','A closed system makes it possible to compare the same total amount of matter.','With an adult, predict and compare the mass of sealed ice before and after melting. Keep the outside dry.'],['Food webs connect','Plants use sunlight to help make food. Animals obtain matter and energy by eating plants or other animals. Decomposers break down dead material. A food web represents several connected feeding relationships. Removing one population may affect more than its immediate predator because relationships overlap.','Why is a web often more useful than one food chain?','it shows several connected feeding relationships|it shows every individual animal|it proves populations never change','Food webs represent multiple connections among organisms.','Draw a simple habitat food web and label what each arrow means.']],
[['Particles on the move','Matter is made of particles. In a gas, particles move and spread through available space. In a liquid, particles remain close but can move past one another. A model helps explain observations, but drawn circles are representations rather than a photograph of individual particles.','What should we remember about a particle diagram?','it is a model with limits|it shows particles at actual size|particles are always colored circles','Models represent selected features and do not reproduce every detail of reality.','Draw particle models for a liquid and gas. Write one useful feature and one limitation of your drawings.'],['An ecosystem changes','A drought can reduce available water, changing plant growth and food supplies. Populations may respond differently, and several causes can act together. Scientists compare observations over time before explaining a change. A correlation between two trends is a clue to investigate, not automatic proof that one caused the other.','What strengthens an explanation of a population change?','evidence over time and consideration of other causes|one dramatic picture|assuming the first guess is correct','Multiple observations and alternative explanations help evaluate the proposed cause.','Read a habitat account with a grown-up. List observations separately from possible explanations.']]
],
history:[
[['First, next, last','A sequence puts events in order. Think about getting ready to go outside: first find shoes, next put them on, then walk to the door. Pictures can help us tell what happened. Different families may use different routines, and we can describe our own without calling another routine wrong.','What does a sequence show?','the order of events|how heavy a shoe is|the color of a door','First, next, and last help explain order.','Draw three pictures of a familiar routine and tell a grown-up their order.'],['A memory object','An object can remind someone of a past event. A small shell might remind a person of a beach visit. The shell alone cannot tell us every detail. Asking the person about it adds a story, and the person may not remember everything.','What can help explain why a shell matters to someone?','asking about their memory|weighing it only|assuming all shells have the same story','A person’s account can explain the object’s connection to an event.','Choose an everyday object and tell a trusted grown-up a memory connected to it.']],
[['Then and now at school','Photographs can show how a classroom looked in the past. Compare desks, writing tools, and clothing. Some things change while other things remain similar. A photograph shows one place at one moment, so it cannot show how every school looked.','What can one classroom photograph show?','one classroom at one moment|every school in the world|all future classrooms','A photograph is evidence with a particular place and time.','Compare a historical classroom picture from a library book with your classroom.'],['Ask a good history question','A question beginning with how can invite an explanation. Ask a trusted adult how they traveled to school when young. Listen, then ask a follow-up about a detail. Their memory describes an experience; another person may have had a different one.','Which question invites an explanation?','How did you travel to school?|Was it school?|Is this a pencil?','A how question can invite the speaker to describe an experience.','Interview a trusted grown-up and draw one detail from their answer.']],
[['A timeline of a project','A timeline organizes events by when they happened. Record planting a seed, noticing a sprout, and seeing leaves. Dates help compare the gaps between events. Putting events in order does not alone explain why they happened. To explain growth, we need observations and knowledge about plants too.','What does a dated timeline help compare?','the time between events|the exact cause of every event|the weight of every plant','Dates show sequence and allow comparisons of elapsed time.','Make a three-event timeline from a project you remember.'],['Two memories of one event','Two people may remember different details of the same picnic. One remembers rain; another remembers sharing food under a shelter. Both accounts may add information. Ask when each person was present and what they could see before deciding that one difference means someone is wrong.','What is a helpful response to different accounts?','ask about each person’s viewpoint|discard both immediately|choose the longer account automatically','Viewpoint and opportunity to observe help explain differences.','Tell a shared event with a grown-up and compare the details each of you remembers.']],
[['A source has a creator','A letter, photograph, or diary was made by someone for a reason. Ask who created it, when, and for whom. A diary may show personal feelings while a public notice may explain rules. Understanding purpose helps us interpret what a source includes and leaves out.','Why ask who a source was made for?','its audience can influence its content|audience determines its weight|all sources have identical purposes','Creators choose information and language for an audience.','Examine a public notice and explain who it addresses and what it asks them to do.'],['Change and continuity','A town may add a bridge while keeping an old market. Studying history includes changes and things that continue. Compare sources from more than one date. A new building does not mean everything about a community changed at the same moment or in the same way.','What is continuity?','something remaining over time|every building being new|a guess about tomorrow','Continuity describes features that persist while other things change.','Draw a then-and-now comparison with one change and one similarity.']],
[['Trade leaves evidence','A traded object can suggest connections between places. Its material and style may provide clues about where it was made. But an object can move through several owners. Historians combine objects with records and other evidence rather than assuming its final location reveals its entire journey.','Why combine an object with written records?','each can add evidence about its journey|records make objects older|one object proves every trade route','Different sources can support, refine, or challenge an explanation.','Invent an object’s possible journey and mark which parts are evidence and which are guesses.'],['Cause is often plural','An event can have several causes. A community might build a bridge because of trade, difficult travel, and population growth. Causes can interact, and people may disagree about their importance. A careful explanation connects each proposed cause to evidence instead of listing reasons without support.','What improves a causal explanation?','connecting proposed causes to evidence|choosing the shortest reason|ignoring all but one source','Evidence helps readers assess how each cause contributed.','Explain two possible reasons for a community improvement and what evidence you would seek.']],
[['Compare a primary and secondary source','A diary written during an event is a primary source for its writer’s experience. A later history book interpreting that event is a secondary source. Neither label guarantees accuracy. Ask what each source can show, what its creator knew, and how other evidence supports its claims.','Does being a primary source guarantee accuracy?','no, its claims still need evaluation|yes, memories never fail|yes, every detail is complete','Source type describes a relationship to the topic, not a guarantee of truth.','Compare a short diary excerpt and a later account selected by a grown-up.'],['Whose voice is missing?','A record may preserve officials’ decisions while saying little about people affected by them. Ask whose perspectives are represented and whose are absent. Missing evidence limits conclusions. We can search for other sources while avoiding invented quotations or assumptions about what an absent person must have thought.','What should we do when a perspective is missing?','seek more evidence and acknowledge the gap|invent a quotation|assume everyone agreed','Recognizing missing voices supports a more careful account.','Read a historical summary and list people discussed versus people directly quoted.']],
[['Corroborate a claim','Corroboration means checking a claim against other evidence. Two accounts may agree because one copied the other, so agreement alone is not enough. Investigate independence, dates, purpose, and opportunity to observe. A strong explanation shows both supporting evidence and unresolved contradictions.','Why ask whether two accounts are independent?','one may have copied the other|independent accounts are always true|copying changes the date of an event','Repeated information from one origin is not the same as independent confirmation.','Choose a historical claim and outline how you would check it with two different kinds of sources.'],['Interpretation can change','New evidence can lead historians to revise an explanation. A newly found record may add a perspective or challenge an assumption. Revising a claim in response to evidence is a strength. Explain what changed and why, while distinguishing the evidence from your interpretation of it.','When is revising an interpretation justified?','when relevant evidence changes the explanation|when a title sounds exciting|when a claim is repeated louder','Interpretations should respond to the quality and relevance of evidence.','Write an initial explanation of a pictured scene, then revise it after a grown-up reveals another detail.']]
],
geography:[
[['Near and far','Words such as near, far, beside, and behind describe positions. A chair may be near a table but far from the door. These descriptions depend on the reference object. Saying near without explaining near what may leave a listener unsure.','Which direction is clearest?','Put the book beside the lamp.|Put it near.|Put it somewhere.','Naming the reference object helps a listener locate the place.','Describe a toy’s position without pointing and ask a grown-up to find it.'],['Land and water','A map may use colors and symbols for land and water. Read its key because mapmakers can choose different symbols. A blue area often represents water, but the key tells us what it means on this particular map. Models show selected features of real places.','How can you check what a map color means?','read the map key|guess from its brightness|count the letters in the title','The key explains the map’s symbols and colors.','Draw an imaginary island and add a key for land and water.']],
[['A map from above','A simple map can show a room as if you were looking down from above. Rectangles might represent tables, and a gap may mark a door. A map does not need to draw every detail. Choose features that help someone understand the space.','What makes a room map useful?','showing important features and their positions|drawing every scratch|using no symbols','Selected features and relative positions help people understand a space.','Draw your room from above with a door and two large objects.'],['Follow a route','A route describes a way from one place to another. It needs a starting point and directions in a sensible order. Try explaining a route on a paper map. If a partner gets lost, add a landmark or clarify which turn comes next.','What does a route need first?','a starting point|a weather forecast|the oldest building','Directions become meaningful when the traveler knows where to begin.','Make a pretend map and guide a grown-up from a library to a park.']],
[['Symbols save space','A map symbol stands for a real feature. A small tree icon might mark a park, not just one tree. The legend explains the symbol. Using the same symbol consistently helps readers compare places and prevents a map from becoming crowded with long labels.','Why check the legend for a tree icon?','it might represent a whole park|it proves the tree is tallest|all map icons mean the same thing','The legend tells you what the symbol represents on that map.','Create a neighborhood map with three symbols and a matching legend.'],['People use places','People use places for homes, work, growing food, and recreation. One area may serve several purposes. When planning a park, people may consider space, access, shade, and nearby roads. Different needs can lead to different suggestions, so listening helps compare choices.','What helps compare possible park sites?','considering access, space, and users’ needs|choosing only the brightest color|ignoring nearby roads','Several features affect how well a place serves a purpose.','Draw two pretend park sites and explain one benefit of each.']],
[['Use a compass rose','A compass rose shows directions on a map. North is often at the top, but check the map rather than assuming. If a school is east of a park, the park is west of the school. Direction describes a relationship between places.','A school is east of a park. Where is the park relative to the school?','west|east|north','Opposite viewpoints reverse east and west in this relationship.','Draw a compass rose and place a school east of a park.'],['A region needs a rule','A region groups places by a shared feature, such as climate, language, or landform. Different rules can create different regions. A mountain region and a rainfall region may overlap without having identical boundaries. Always ask which feature was used to group the places.','Why might two regional maps have different boundaries?','they group places by different features|one must be imaginary|regions never overlap','Regional boundaries depend on the feature and purpose of the grouping.','Group imaginary places first by rainfall and then by landform. Compare the groups.']],
[['Read a scale','A map scale connects distance on a map to distance on the ground. If one centimeter represents one kilometer, three centimeters represent three kilometers. A straight-line distance is not always the same as a walking route, because roads can bend around obstacles.','Why can a walking route be longer than a straight-line distance?','roads may bend around obstacles|kilometers change size|the map key disappears','A route follows available paths, which may not be straight.','Draw two places with a scale and compare a straight line with a winding route.'],['Water shapes settlement','People often establish communities near water for drinking, farming, travel, or trade. Water can also bring risks such as flooding. A place can offer both benefits and challenges. Studying the landscape helps explain choices without assuming that every community developed for one identical reason.','Which statement considers both benefits and challenges?','a river can support travel and also flood|rivers are always safe|water never affects settlement','Geographic features can create opportunities and risks together.','Sketch a riverside town and label one useful feature and one challenge to plan for.']],
[['Latitude and longitude','Latitude describes position north or south of the equator. Longitude describes position east or west of the prime meridian. Coordinates use both to locate a place. These reference lines are part of a geographic system; they are not painted across the actual land and water.','Which measurement describes north or south of the equator?','latitude|longitude|elevation','Latitude measures angular position north or south of the equator.','On a globe with a grown-up, find the equator and compare two places north of it.'],['A map has a purpose','A road map emphasizes routes, while a rainfall map emphasizes precipitation patterns. Each selects information for a purpose. Leaving out details can make a map useful, but readers should notice what is omitted. The best map depends on the question you are trying to answer.','Which map best supports comparing rainfall patterns?','a rainfall map|a bus-seat diagram|a street-name list','A thematic rainfall map emphasizes the information needed for that comparison.','Choose a question about a place and design a map legend suited to answering it.']],
[['Projection changes a view','A globe represents Earth’s curved surface. Flattening that surface onto a map introduces distortion. Different projections preserve different properties, such as shapes or relative areas. No flat world map preserves all distances, areas, shapes, and directions everywhere. Choose and interpret maps with their purpose in mind.','Why compare map projections?','they distort properties in different ways|one shows every property perfectly|Earth changes shape between maps','Projection choices affect how the curved surface is represented on a flat map.','Compare two world maps in library resources and discuss how the same region looks different.'],['Connections across places','A product may connect farms, factories, transport routes, shops, and households in different places. A supply-chain map can show these links. Its arrows should explain what moves, and its sources should support the locations. A simple chain leaves out many details, so label its limits.','What should an arrow on a supply-chain map explain?','what moves between the places|the favorite color of a worker|which place is always best','An explained arrow makes the relationship between locations clear.','With a grown-up, trace the known places on a food label and mark any steps you cannot verify.']]
]
};
Object.entries(inquiry).forEach(([subject,grades])=>grades.forEach((rows,grade)=>rows.forEach(([title,teach,question,choices,explanation,activity],i)=>{const options=choices.split('|'),answer=(grade+i)%3;for(let n=0;n<answer;n++)options.unshift(options.pop());C.lessons.push({id:`extra-${subject}-${grade}-${i}`,grade,subject,kind:'inquiry',title,objective:teach.split('. ')[0]+'.',teach,question,options,answer,explanation,activity,standard:null,minutes:12,order:100+i});})));
})(typeof globalThis!=='undefined'?globalThis:this);
