(function(root){
'use strict';
const C=root.WonderCurriculum;
const specs=[
[0,'count-five','Touch, move, count','Count up to five objects once each.','K.CC.B.4','Move each large counter to a new space as you count. The last number tells how many.'],
[0,'zero-five','An empty nest','Connect zero through five with quantities.','K.CC.A.3','Make a nest with no counters. Say zero. Add counters one at a time and name each new total.'],
[0,'same-set','Spread them, count them','Notice that rearranging a set does not change its total.','K.CC.B.4b','Count a row of counters, spread the same counters out, then count again. None were added or removed.'],
[0,'compare-five','Match one to one','Compare small sets by pairing their objects.','K.CC.C.6','Place one counter from each group side by side. The group with unpaired counters has more.'],
[1,'count-on','Start here, count on','Count on from a known quantity within ten.','1.OA.C.5','Build the starting group. Say its total, then say one new number for each counter you add.'],
[1,'parts-ten','Ten has two parts','Find a missing part of ten with a model.','1.OA.C.6','Put ten large counters in two rows of five. Cover one part and use the visible part to find the hidden part.'],
[1,'join-ten','Tell a joining story','Connect a joining story to an addition equation within ten.','1.OA.A.1','Build the first group, add the new group, and explain what each number in your equation means.'],
[1,'take-ten','Tell a taking-away story','Connect taking away to subtraction within ten.','1.OA.A.1','Make the starting group and move away the part that leaves. Count what remains and check by putting the parts back together.']
];
const lessons=specs.map(([grade,k1Mode,title,objective,standard,activity],i)=>({id:'k1-year-m-'+grade+'-'+(i%4+1),grade,subject:'maths',kind:'math',k1Mode,title,objective,standard,activity,minutes:10,order:400+i,reviewStatus:'educator-review-needed'}));
C.lessons.push(...lessons);const prior=C.problem;
C.problem=function(l,seed=0){if(!l.k1Mode)return prior(l,seed);const k=Math.abs(Math.trunc(seed))%5;let prompt,answer,steps,visual;switch(l.k1Mode){
case'count-five':answer=k+1;prompt='How many counters are in this group?';visual={type:'k1-dots',n:answer};steps=['Touch or point to each counter once.','Say one number for each counter: '+Array.from({length:answer},(_,i)=>i+1).join(', ')+'.','The last number is '+answer+', so the group has '+answer+' counters.'];break;
case'zero-five':answer=[0,2,4,1,5][k];prompt='How many counters are in the nest?';visual={type:'k1-dots',n:answer};steps=answer?['Count each counter once.','The last count is '+answer+'. Match that quantity to the numeral '+answer+'.']:['There are no counters in the nest.','Zero means none of these objects. Write or choose 0.'];break;
case'same-set':answer=k+1;prompt='Pip counted '+answer+' counters, then spread those same counters apart. None were added or removed. How many now?';visual={type:'k1-dots',n:answer};steps=['Changing the spaces between counters does not add or remove any.','Point and count to check: there are still '+answer+'.'];break;
case'compare-five':{const a=k%4+1,b=a+1;answer=b;prompt='One nest has '+a+' counters. Another has '+b+'. Which number tells the larger group?';visual={type:'counters',a,b,op:'and'};steps=['Match one counter from each nest until one nest has none left to pair.','The group of '+b+' has one unpaired counter.','So '+b+' is more than '+a+'.'];break;}
case'count-on':{const a=k+3,b=2;answer=a+b;prompt='There are '+a+' birds. Two more arrive. How many now?';visual={type:'counters',a,b,op:'+'};steps=['Start with the known total '+a+'. Do not count the starting group again.','Count on two: '+(a+1)+', '+answer+'.','There are '+answer+' birds now.'];break;}
case'parts-ten':{const a=k+3;answer=10-a;prompt='Ten counters are in a frame. '+a+' are red. The rest are blue. How many are blue?';visual={type:'ten',n:a};steps=['The frame holds ten. '+a+' places are filled with red counters.','Count the empty places that will hold the blue counters: '+answer+'.','Check the whole: '+a+' + '+answer+' = 10.'];break;}
case'join-ten':{const a=k+2,b=3;answer=a+b;prompt='Pip puts '+a+' shells in a tray, then adds '+b+' more. How many shells altogether?';visual={type:'counters',a,b,op:'+'};steps=['The first part has '+a+' shells. The new part has '+b+'.','Join the groups or count on '+b+' from '+a+'.','The equation '+a+' + '+b+' = '+answer+' describes this story.'];break;}
case'take-ten':{const a=k+5,b=2;answer=a-b;prompt='There are '+a+' blocks. Pip takes away '+b+'. How many blocks remain?';visual={type:'k1-dots',n:a};steps=['Build the starting group of '+a+'.','Move away '+b+' blocks. Count the remaining '+answer+'.','Check by joining the parts: '+answer+' + '+b+' = '+a+'.'];break;}}
return{mode:l.k1Mode,prompt,answer,display:String(answer),steps,visual,options:null};};
// Original planning sequence. A topic is not a completed unit or an endorsed curriculum.
const raw=[
[
'Our first discoveries|Touch and count to five~Zero and numerals~Same set, new arrangement~Compare by matching|Letters m s a p~Letters t n i c~Letters b f o d~Letters g e h k|Observe with senses and describe evidence|Daily order, familiar places and simple maps|Draw a discovery and dictate a sentence',
'Letters and quantities|Count six to ten~Match numerals to sets~One more and one less~Classify and count groups|Letters l u r w~Letters j v y z~Letters q x and review~Blend short-a words|Compare properties of safe materials|People who help and shared responsibilities|Label a drawing with known letters',
'Build and blend|Compose numbers to five~Take apart to five~Joining stories to five~Taking-away stories to five|Blend short-i words~Blend short-u words~Compare a i u~Change first and last sounds|Pushes, pulls and changes in motion|Before and after; clues from objects|Tell a beginning, middle and end',
'Patterns we can explain|Count to twenty~Write numerals to twenty~Compare sets to ten~Review joining and separating|Blend short-e words~Blend short-o words~Compare all short vowels~Read simple sentences|Needs of plants and animals|Places on maps; land and water|Draw and dictate an information page',
'Ten and some more|Make ten~Teen numbers as ten and ones~Build eleven to fifteen~Build sixteen to nineteen|Onset and rime~Blend and segment spoken words~Common helper words~Reread for meaning|Weather observations and seasonal patterns|Clothes, shelter and places in different weather|State an opinion and give a reason',
'Shape explorers|Name flat shapes~Name solid shapes~Position and direction~Compose shapes|Long and short vowel names~Distinguish similar spellings~Retell key events~Ask about an information text|Sunlight warms surfaces; design shade|Describe a route and use location words|Describe a place with precise words',
'Measure and compare|Longer and shorter~Heavier and lighter~Sort by two attributes~Compare category counts|Sequence a story~Connect pictures and text~Compare characters~Write familiar words|Observe living things and their surroundings|Families and traditions; similarities and differences|Revisit and add detail to a drawing and sentence',
'Solve and explain|Addition stories within ten~Subtraction stories within ten~Fluency within five~Missing parts to ten|Recall sound patterns~Read short connected text~Explain an answer with a detail~Share a short retelling|Reduce waste and care for shared places|Fair choices, rules and community care|Make a small book with adult support',
'Share our discoveries|Count to one hundred by ones~Count to one hundred by tens~Mixed number and shape problems~Review and explain strategies|Cumulative decoding review~Read and discuss a new text~Share writing and listen~End-year reading portfolio|Plan and explain a simple investigation|Use a map and sequence evidence about the past|Select, improve and present favorite work'
],[
'Our learning toolkit|Count on within ten~Parts of ten~Joining stories within ten~Taking-away stories within ten|Review short vowels and sh~Read ch words~Keep every consonant sound~Compare teams and consonant groups|Observe plant parts and needs|Then and now; map symbols and routes|Write a complete sentence about an observation',
'Words and number relationships|Related addition and subtraction~Missing addends~True and false equations~Meaning of the equals sign|Compare short a and long a~Compare short i and long i~Read final consonant groups~Review short vowels and silent e|Compare animals and their external parts|Ask questions about community history|Tell events in order using sentences',
'Build a ten|Make-ten addition within twenty~Doubles and near doubles~Subtract through ten~Three addends within twenty|Long o and long u with final e~Common vowel teams~Read th and wh~Read ck and ng|Parents and young; patterns of behavior|Use sources and distinguish past and present|Describe a topic and add two facts',
'Counting and place value|Count and write to one hundred twenty~Ten ones make one ten~Read tens and ones~Compare two-digit numbers|Syllables and vowel sounds~Read two-syllable words~Read words ending s and es~Read ing and ed endings|Light sources, dark places and safe observations|Maps, globes, land, water and landmarks|State an opinion with a reason and ending',
'Use place value|Ten more and ten less~Add a two-digit number and ones~Add two-digit numbers and tens~Subtract multiples of ten|Irregular helper words~Reread with expression~Self-correct by rereading~Explain a story with details|Sound and vibrations|Communication across places and time|Expand sentences and revise unclear words',
'Measure our world|Order three lengths~Measure with equal units~Compare lengths indirectly~Solve measurement stories|Ask and answer text questions~Describe characters and settings~Retell central events~Compare stories|Design a light or sound signal|Community decisions and responsibilities|Write and explain a simple set of directions',
'Shapes, parts and time|Build and describe shapes~Compose flat and solid shapes~Equal halves and fourths~Time to hour and half hour|Find main topic and details~Use headings and pictures~Compare two information texts~Explain vocabulary in context|Patterns in the day and night sky|Traditions and contributions of different communities|Collect facts and make a short information book',
'Data and problem solving|Organize three-category data~Compare category counts~Change-unknown stories~Compare and put-together problems|Cumulative spelling patterns~Read dialogue with expression~Support an answer with text~Revise a narrative|Changing daylight across seasons|Read a simple timeline and compare evidence|Share writing, listen and respond to questions',
'Apply and reflect|Fluency within ten~Mixed addition and subtraction within twenty~Place-value and geometry projects~End-year strategy portfolio|Read unfamiliar regular words~Read a new text for meaning~Share a reading and writing portfolio~Review and plan next steps|Explain an investigation and improve a design|Combine a map, timeline and community story|Publish a chosen piece with a clear beginning and ending'
]
];
const openingReading=[['letter-foundations-0-1','letter-foundations-0-2','letter-foundations-0-3','letter-foundations-0-4'],['literacy-pilot-1-ship','literacy-pilot-1-chin','literacy-pilot-1-stop','literacy-pilot-1-compare']];
const openingInquiry=[['scienceLab-0-0','growth-scienceLab-0-1','history-0-0','geography-0-0'],['growth-scienceLab-1-0','scienceLab-1-0','history-1-0','geography-1-0']];
const weeks=raw.map((blocks,grade)=>blocks.flatMap((line,b)=>{const[theme,math,reading,science,social,writing]=line.split('|');return math.split('~').map((focus,i)=>({grade,number:b*4+i+1,theme,math:focus,reading:reading.split('~')[i],science,social,writing,mathLesson:b===0?'k1-year-m-'+grade+'-'+(i+1):null,readingLesson:b===0?openingReading[grade][i]:null,inquiryLesson:b===0?openingInquiry[grade][i]:null,status:b===0?'starter-activities':'planned'}));}));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(grade,selected=1,day=0,entries={}){const week=weeks[grade][Math.max(0,Math.min(35,Number(selected)-1||0))];const link=(id,label)=>id?'<button class="primary" data-lesson="'+id+'">'+label+'</button>':'<p>Detailed activities for this focus are being authored.</p>';const math=C.lessons.find(l=>l.id===week.mathLesson);return '<section class="panel"><h2>Your 36-week learning map</h2><p>Kindergarten and Grade 1 are our current build priority. This is a draft scope and sequence, not a completed full-year curriculum. Weeks 1–8 include daily plans and related practice; later topics are planning entries. Educator review is pending.</p><label for="k1-week">Choose a week</label> <select id="k1-week">'+weeks[grade].map(w=>'<option value="'+w.number+'" '+(w.number===week.number?'selected':'')+'>Week '+w.number+' · '+esc(w.math)+'</option>').join('')+'</select></section><section class="panel"><p>WEEK '+week.number+' · '+(week.status==='planned'?'PLANNING ENTRY':'STARTER ACTIVITIES AVAILABLE')+'</p><h2>'+esc(week.theme)+'</h2><h3>Math: '+esc(week.math)+'</h3>'+link(week.mathLesson,'Explore this math idea')+(math?'<p><strong>Try away from the screen:</strong> '+esc(math.activity)+' Use large, safe objects with a grown-up.</p>':'')+'<h3>Reading: '+esc(week.reading)+'</h3>'+link(week.readingLesson,'Open word work')+'<h3>Writing and speaking</h3><p>'+esc(week.writing)+'. A grown-up may scribe while the child tells their idea. Revisit the work together.</p><h3>Science focus</h3><p>'+esc(week.science)+'.</p><h3>History and geography focus</h3><p>'+esc(week.social)+'.</p>'+link(week.inquiryLesson,'Try a related investigation')+'</section>'+(root.WonderOpeningMonth?.render(grade,week.number,day,entries)||'')+'<section class="panel"><h2>A flexible week</h2><ol><li>Explore a new idea with a grown-up and a concrete model.</li><li>Try it again using different objects, words or examples.</li><li>Apply it in a story, drawing, question or investigation.</li><li>Return to an earlier skill and explain a connection.</li><li>Share work and choose what to revisit next.</li></ol><p>Read aloud and discuss a book every day; include play, movement, art and breaks. Daily plans for weeks 1–8 appear above when available. Detailed plans for later weeks are still being developed. A finished lesson records practice, not mastery of a week.</p></section>';}
root.WonderK1Year={weeks,lessons,render};
})(globalThis);
