(function(root){
'use strict';
const day=86400000;
function schedule(previous,independent,now=new Date()){const level=independent>=.8?Math.min(4,(previous?.reviewLevel||0)+1):0;return{reviewLevel:level,reviewDue:new Date(+now+[1,1,3,7,14][level]*day).toISOString()};}
function dueLessons(lessons,results,now=new Date()){const due=r=>Date.parse(r?.reviewDue)||(Date.parse(r?.last)+day);return lessons.filter(l=>results[l.id]?.completed&&Number.isFinite(due(results[l.id]))&&due(results[l.id])<=+now).sort((a,b)=>due(results[a.id])-due(results[b.id]));}
function steps(a,b,op){if(![a,b].every(n=>Number.isInteger(n)&&n>=0&&n<=9999)||op==='−'&&a<b)return[];const labels=['ones','tens','hundreds','thousands','ten-thousands'],out=[];
if(op==='+'){let carry=0;for(let i=0;i<Math.max(String(a).length,String(b).length);i++){const x=Math.floor(a/10**i)%10,y=Math.floor(b/10**i)%10,sum=x+y+carry;out.push({question:`In the ${labels[i]} column, what is ${x} + ${y}${carry?' + 1 carried':''}?`,answer:sum,hint:`Count ${x} ${labels[i]}, then add ${y}${carry?' and the carried 1':''}.`,explanation:sum>=10?`${sum} ${labels[i]} can be regrouped. Write ${sum%10} here and carry 1 to the next column.`:`Write ${sum} in the ${labels[i]} column.`});carry=Math.floor(sum/10);}}
else if(op==='−'){const d=String(a).split('').reverse().map(Number);for(let i=0;i<d.length;i++){const y=Math.floor(b/10**i)%10;let intro='';if(d[i]<y){let k=i+1;while(d[k]===0)k++;d[k]--;for(let j=k-1;j>i;j--)d[j]=9;d[i]+=10;intro=`First regroup from the ${labels[k]} place. Now you have ${d[i]} ${labels[i]}. `;}out.push({question:`${intro}In the ${labels[i]} column, what is ${d[i]} − ${y}?`,answer:d[i]-y,hint:`Start at ${d[i]} and take away ${y}.`,explanation:`Write ${d[i]-y} in the ${labels[i]} column.`});}}
else if(op==='×'){for(let i=0;i<String(b).length;i++){const part=Math.floor(b/10**i)%10*10**i;out.push({question:`One part of ${b} is ${part}. What is ${a} × ${part}?`,answer:a*part,hint:`Multiply ${a} by ${part/10**i}, then multiply by ${10**i}.`,explanation:`This partial product is ${a*part}. Keep it to combine with the other parts.`});}out.push({question:`Add your partial products. What is ${a} × ${b}?`,answer:a*b,hint:'Combine all the partial products you just found.',explanation:`The total product is ${a*b}.`});}
else if(op==='÷'&&b>0){let remainder=0;for(const digit of String(a)){const total=remainder*10+Number(digit),q=Math.floor(total/b);out.push({question:`Bring down ${digit}. You now have ${total}. How many groups of ${b} fit?`,answer:q,hint:`Find the largest whole number whose product with ${b} is at most ${total}.`,explanation:`${q} × ${b} = ${q*b}. Subtract to leave ${total-q*b}.`});remainder=total-q*b;}if(remainder)out.push({question:'What remainder is left after the last step?',answer:remainder,hint:'Use the last subtraction result.',explanation:`The quotient is ${Math.floor(a/b)}, with remainder ${remainder}.`});}
return out;}
function fromProblem(p){const m=p.prompt.match(/^(\d+)\s*([+−×÷])\s*(\d+)$/);return m?steps(Number(m[1]),Number(m[3]),m[2]):[];}
function sentences(text){return text.match(/[^.!?]+[.!?]+[”’"']?|[^.!?]+$/g)?.map(s=>s.trim()).filter(Boolean)||[text];}
function validateBackup(input,ids){if(!input||typeof input!=='object'||!['Wonderwild Academy','Wonderwild'].includes(input.app))throw new Error('Choose a Wonderwild progress export.');const incoming=input.learning||input;const allowed=new Set(ids),results=Object.create(null);if(incoming.results&&typeof incoming.results==='object'&&!Array.isArray(incoming.results))for(const [id,r]of Object.entries(incoming.results)){if(!allowed.has(id)||!r||r.completed!==true||!Number.isFinite(Date.parse(r.last)))continue;if(!Number.isFinite(r.recentIndependent)||r.recentIndependent<0||r.recentIndependent>1)continue;const bound=(v,max)=>Number.isInteger(v)&&v>=0?Math.min(v,max):0;results[id]={completed:true,last:new Date(r.last).toISOString(),visits:Math.max(1,bound(r.visits,100000)),recentIndependent:r.recentIndependent,bestIndependent:Math.max(r.recentIndependent,Number.isFinite(r.bestIndependent)?Math.min(1,Math.max(0,r.bestIndependent)):0),checks:bound(r.checks,1000),misses:bound(r.misses,10000),evidence:Array.isArray(r.evidence)?r.evidence.slice(0,20).filter(e=>e&&Number.isInteger(e.index)&&e.index>=0&&e.index<20&&Number.isInteger(e.attempts)&&e.attempts>0&&e.attempts<=10000).map(e=>({index:e.index,attempts:e.attempts,firstTry:e.firstTry===true&&e.attempts===1})):[],reviewLevel:bound(r.reviewLevel,4),reviewDue:Number.isFinite(Date.parse(r.reviewDue))?new Date(r.reviewDue).toISOString():new Date(Date.parse(r.last)+day).toISOString()};}
const original=input.original||input,stories=[];if(Array.isArray(original.stories))for(const s of original.stories.slice(0,100)){if(s&&typeof s.text==='string'&&s.text.trim()&&s.text.length<=5000&&Number.isFinite(Date.parse(s.date)))stories.push({text:s.text,date:new Date(s.date).toISOString()});}const completed=Array.isArray(original.completed)?[...new Set(original.completed.filter(k=>/^(story|math|science|logic)-[0-2]$/.test(k)))]:[];
const yearEntries=Object.create(null);if(incoming.yearEntries&&typeof incoming.yearEntries==='object')for(const[key,r]of Object.entries(incoming.yearEntries)){if(!/^(?:[1-9]|[12]\d|3[0-6])-[0-4]-(?:math|reader|science|words|social|write|review|share|reflect|reading-time)$/.test(key)||!r||!Number.isFinite(Date.parse(r.updated)))continue;yearEntries[key]={done:r.done===true,note:typeof r.note==='string'?r.note.slice(0,2000):'',updated:new Date(r.updated).toISOString()};}if(!Object.keys(results).length&&!stories.length&&!completed.length&&!Object.keys(yearEntries).length)throw new Error('This export contains no valid lesson results, stories, or island progress.');return{results,stories,completed,yearEntries};}
function mergeResults(current,incoming){const merged={...current};for(const[id,r]of Object.entries(incoming)){if(!merged[id]||Date.parse(r.last)>Date.parse(merged[id].last))merged[id]=r;}return merged;}
root.WonderLearning={schedule,dueLessons,steps,fromProblem,sentences,validateBackup,mergeResults};if(typeof module!=='undefined')module.exports=root.WonderLearning;
})(typeof globalThis!=='undefined'?globalThis:this);
