(function(root){
'use strict';
// Original Wonderwild practice. No CKLA text, assessment items, or artwork.
const rows=[
 [0,'map','Map makers','Blend short-a words with m, a, p, s, and t.','Know the sounds for m, a, p, s, and t.','Point to each spelling and say its sound. Slide the sounds together to read the word. The middle sound in map is the short a sound.',['map','mat','sat','tap'],['m · a · p','m · a · t','s · a · t','t · a · p'],[
 ['Which word ends with p?',['mat','map','sat'],1,'Map ends with p. Mat and sat end with t.'],['Change the p in map to t. What word do you make?',['sat','tap','mat'],2,'Keep m and a, then replace p with t: mat.'],['Which word starts with s?',['sat','map','tap'],0,'Sat begins with s. Read the remaining a and t to finish the word.']]],
 [0,'it','Pip packs a kit','Read short-i words and compare their spellings.','Know the sounds for s, i, t, p, n, and k.','The middle sound in sit is short i. Keep that middle sound as you blend each new word. Read the letters in order; do not guess from the first letter.',['sit','sip','pin','kit'],['s · i · t','s · i · p','p · i · n','k · i · t'],[
 ['Which word names something you do on a chair?',['sip','sit','pin'],1,'Sit means to rest on a seat. Check all three letters: s, i, t.'],['Which word ends with n?',['kit','sit','pin'],2,'Pin ends with n. Listen as a grown-up says pin slowly.'],['Change the last letter in sit to p. What do you get?',['sip','kit','pin'],0,'The beginning s and middle i stay the same. The new word is sip.']]],
 [0,'sun','A sunny picnic','Blend short-u words without guessing.','Know the sounds for s, u, n, c, p, b, and g.','The middle sound in sun is short u. Look at the first spelling, the middle spelling, and the last spelling. Join their sounds to read each word.',['sun','cup','bus','bug'],['s · u · n','c · u · p','b · u · s','b · u · g'],[
 ['Which word ends with g?',['bus','bug','sun'],1,'Bug ends with g. Bus ends with s.'],['Which word begins with c?',['sun','bus','cup'],2,'Cup starts with c, representing the k sound here.'],['Change the g in bug to s. Which word appears?',['bus','sun','cup'],0,'B and u stay in place. Replacing g with s makes bus.']]],
 [0,'mix','The mixed-up labels','Distinguish short a, i, and u in familiar words.','Practise Map makers, Pip packs a kit, and A sunny picnic first.','The middle vowel can change a whole word. Read all the spellings. Mat, sit, and sun use different middle vowels. Ask a grown-up to model any sound you do not know.',['mat','sit','sun','cup'],['m · a · t','s · i · t','s · u · n','c · u · p'],[
 ['Which word has the same middle vowel letter as map?',['sit','sun','mat'],2,'Map and mat both have a in the middle.'],['Which word has the same middle vowel sound as bug?',['cup','mat','sit'],0,'Cup and bug both have short u.'],['Which word has i in the middle?',['sun','sit','mat'],1,'Sit has i between s and t. Say and blend all three sounds.']]],
 [1,'ship','Ships and shells','Read sh as a two-letter spelling for one sound.','Blend short-vowel words; know i, o, p, and t.','The letters s and h can work together as sh. In ship, sh is one sound, followed by i and p. Keep the letter team together when you blend.',['ship','shop','shut','fish'],['sh · i · p','sh · o · p','sh · u · t','f · i · sh'],[
 ['Which spelling is the letter team in ship?',['ip','sh','hi'],1,'S and h work together to represent sh.'],['How many speech sounds are in fish?',['Four','Two','Three'],2,'Fish has three sounds: f, short i, and sh. Two letters can represent one sound.'],['Change the i in ship to o. Which word appears?',['shop','fish','shut'],0,'Keep sh and p. With o in the middle, the word is shop.']]],
 [1,'chin','A chat with Pip','Read ch at the beginning and end of words.','Blend short-vowel words and recognise two-letter sound spellings.','The spelling ch represents one sound in chin. It can also appear at the end, as in much. Count sounds, rather than counting letters, when you blend.',['chin','chat','chop','much'],['ch · i · n','ch · a · t','ch · o · p','m · u · ch'],[
 ['Which word has ch at the end?',['chat','much','chin'],1,'Much ends with the ch spelling.'],['How many speech sounds are in chin?',['Four','Five','Three'],2,'Chin has ch, short i, and n: three sounds.'],['Which word has short a in the middle?',['chat','chop','chin'],0,'Chat has short a. Chop has short o and chin has short i.']]],
 [1,'stop','Stop at the pond','Blend consonant groups while keeping every sound.','Blend short-vowel words and know s, t, p, n, d, l, a, o.','Some words put consonant sounds next to each other. In stop, keep both s and t. They are two sounds, unlike the single sound represented by sh.',['stop','spot','pond','plan'],['s · t · o · p','s · p · o · t','p · o · n · d','p · l · a · n'],[
 ['Which two sounds begin stop?',['s and p','p and l','s and t'],2,'Read in order: s, t, short o, p.'],['How many speech sounds are in pond?',['Four','Three','Two'],0,'Pond has p, short o, n, and d. Keep both ending sounds.'],['Which word ends with t?',['stop','spot','plan'],1,'Spot ends with t. Stop ends with p; letter order matters.']]],
 [1,'compare','The spelling detective','Compare letter teams and consonant groups.','Practise Ships and shells, A chat with Pip, and Stop at the pond.','Look carefully before blending. Sh and ch each represent one sound in these words. In stop, s and t each keep their own sound. Read through to the end.',['shop','chat','stop','pond'],['sh · o · p','ch · a · t','s · t · o · p','p · o · n · d'],[
 ['Which word begins with a two-letter spelling for one sound?',['stop','shop','pond'],1,'Sh is one sound in shop. S and t are separate sounds in stop.'],['Which word has four speech sounds?',['shop','chat','pond'],2,'Pond has four sounds. Shop and chat each have three.'],['Which word has the same middle vowel sound as map?',['chat','shop','stop'],0,'Chat and map use short a. Read chat by joining ch, a, and t.']]]
];
const lessons=rows.map(([grade,key,title,objective,prerequisite,pattern,words,parts,checks],index)=>{
 const questions=checks.map(([question,options,answer,explanation])=>({question,options,answer,explanation}));
 return {id:`literacy-pilot-${grade}-${key}`,subject:'reading',grade,kind:'phonics',title,objective,standard:null,minutes:8,order:200+index,pilot:true,prerequisite,reviewStatus:'educator-review-needed',questions,phonics:{title,objective,pattern,words,parts,question:questions[0].question,contrast:questions[0].options,answer:questions[0].answer},parentPractice:'After the on-screen checks, cover the word and ask your child to say it, then build or write it. Model it again if needed. These oral and paper activities are not automatically scored.'};
});
root.WonderCurriculum.lessons.push(...lessons);
root.WonderLiteracy={lessons};
})(globalThis);
