(function(root){
'use strict';
// Original Wonderwild practice. No CKLA text, assessment items, or artwork.
const rows=[
 [0,'map','Map makers','Blend short-a words with m, a, p, s, and t.','Know the sounds for m, a, p, s, and t.','Point to each spelling and say its sound. Slide the sounds together to read the word. The middle sound in map is the short a sound.',['map','mat','sat','tap'],['m · a · p','m · a · t','s · a · t','t · a · p'],[
 ['Which word ends with p?',['mat','map','sat'],1,'Map ends with p. Mat and sat end with t.'],['Change the p in map to t. What word do you make?',['sat','tap','mat'],2,'Keep m and a, then replace p with t: mat.'],['Which word starts with s?',['sat','map','tap'],0,'Sat begins with s. Read the remaining a and t to finish the word.']]],
 [0,'it','Pip packs a kit','Read short-i words and compare their spellings.','Know the sounds for s, i, t, p, n, and k.','The middle sound in sit is short i. Keep that middle sound as you blend each new word. Read the letters in order; do not guess from the first letter.',['sit','sip','pin','kit'],['s · i · t','s · i · p','p · i · n','k · i · t'],[
 ['Which word names something you do on a chair?',['sip','sit','pin'],1,'Sit means to rest on a seat. Check all three letters: s, i, t.'],['Which word ends with n?',['kit','sit','pin'],2,'Pin ends with n. Listen as a grown-up says pin slowly.'],['Change the last letter in sit to p. What do you get?',['sip','kit','pin'],0,'The beginning s and middle i stay the same. The new word is sip.']]],
 [0,'sun','A sunny picnic','Blend short-u words without guessing.','Know the sounds for s, u, n, c, p, b, and g.','The middle sound in sun is short u. Look at the first spelling, the middle spelling, and the last spelling. Join their sounds to read each word.',['sun','cup','bus','bug'],['s · u · n','c · u · p','b · u · s','b · u · g'],[
 ['Which word ends with g?',['bus','bug','sun'],1,'Bug ends with g. Bus ends with s.'],['Which word begins with c?',['sun','bus','cup'],2,'Cup starts with c, representing the k sound here.'],['Change the g in bug to s. Which word appears?',['bus','sun','cup'],0,'B and u stay in place. Replacing g with s makes bus.']]],
 [0,'mix','The mixed-up labels','Distinguish short a, i, and u in familiar words.','Practise Map makers, Pip packs a kit, and A sunny picnic first.','The middle vowel can change a whole word. Read all the spellings. Mat, sit, and sun use different middle vowels. Ask a grown-up to model any sound you do not know.',['mat','sit','sun','cup'],['m · a · t','s · i · t','s · u · n','c · u · p'],[
 ['Which word has the same middle vowel letter as map?',['sit','sun','mat'],2,'Map and mat both have a in the middle.'],['Which word has the same middle vowel sound as bug?',['cup','mat','sit'],0,'Cup and bug both have short u.'],['Which word has i in the middle?',['sun','sit','mat'],1,'Sit has i between s and t. Say and blend all three sounds.']]],
 [1,'ship','Ships and shells','Read sh as a two-letter spelling for one sound.','Blend short-vowel words; know i, o, p, and t.','The letters s and h can work together as sh. In ship, sh is one sound, followed by i and p. Keep the letter team together when you blend.',['ship','shop','shut','fish'],['sh · i · p','sh · o · p','sh · u · t','f · i · sh'],[
 ['Which spelling is the letter team in ship?',['ip','sh','hi'],1,'S and h work together to represent sh.'],['How many speech sounds are in fish?',['Four','Two','Three'],2,'Fish has three sounds: f, short i, and sh. Two letters can represent one sound.'],['Change the i in ship to o. Which word appears?',['shop','fish','shut'],0,'Keep sh and p. With o in the middle, the word is shop.']]],
 [1,'chin','A chat with Pip','Read ch at the beginning and end of words.','Blend short-vowel words and recognise two-letter sound spellings.','The spelling ch represents one sound in chin. It can also appear at the end, as in much. Count sounds, rather than counting letters, when you blend.',['chin','chat','chop','much'],['ch · i · n','ch · a · t','ch · o · p','m · u · ch'],[
 ['Which word has ch at the end?',['chat','much','chin'],1,'Much ends with the ch spelling.'],['How many speech sounds are in chin?',['Four','Five','Three'],2,'Chin has ch, short i, and n: three sounds.'],['Which word has short a in the middle?',['chat','chop','chin'],0,'Chat has short a. Chop has short o and chin has short i.']]],
 [1,'stop','Stop at the pond','Blend consonant groups while keeping every sound.','Blend short-vowel words and know s, t, p, n, d, l, a, o.','Some words put consonant sounds next to each other. In stop, keep both s and t. They are two sounds, unlike the single sound represented by sh.',['stop','spot','pond','plan'],['s · t · o · p','s · p · o · t','p · o · n · d','p · l · a · n'],[
 ['Which two sounds begin stop?',['s and p','p and l','s and t'],2,'Read in order: s, t, short o, p.'],['How many speech sounds are in pond?',['Four','Three','Two'],0,'Pond has p, short o, n, and d. Keep both ending sounds.'],['Which word ends with t?',['stop','spot','plan'],1,'Spot ends with t. Stop ends with p; letter order matters.']]],
 [1,'compare','The spelling detective','Compare letter teams and consonant groups.','Practise Ships and shells, A chat with Pip, and Stop at the pond.','Look carefully before blending. Sh and ch each represent one sound in these words. In stop, s and t each keep their own sound. Read through to the end.',['shop','chat','stop','pond'],['sh · o · p','ch · a · t','s · t · o · p','p · o · n · d'],[
 ['Which word begins with a two-letter spelling for one sound?',['stop','shop','pond'],1,'Sh is one sound in shop. S and t are separate sounds in stop.'],['Which word has four speech sounds?',['shop','chat','pond'],2,'Pond has four sounds. Shop and chat each have three.'],['Which word has the same middle vowel sound as map?',['chat','shop','stop'],0,'Chat and map use short a. Read chat by joining ch, a, and t.']]]
];
rows.push(
 [0,'hen','A nest for Hen','Read short-e words from left to right.','Know the sounds for h, e, n, p, t, and b. Ask a grown-up to model any unfamiliar sound.','The middle vowel in hen is short e. Say each sound, then slide them together. Keep the middle vowel as you change the beginning or ending.',['hen','pen','pet','ten'],['h · e · n','p · e · n','p · e · t','t · e · n'],[
 ['Change the h in hen to p. Which word do you build?',['pet','pen','ten'],1,'Keep e and n. Replace the first spelling with p to build pen.'],['Which word ends with t?',['hen','pen','pet'],2,'Pet ends with t. Hen and pen both end with n.'],['Which word has the same middle vowel sound as bed?',['ten','tin','tan'],0,'Bed and ten have short e. Ask a grown-up to say both words, then try blending ten.']]],
 [0,'pot','Pip finds a pot','Blend short-o words and change one spelling.','Know the sounds for p, o, t, h, m, d, and g. Ask a grown-up to model short o in pot.','Read pot by joining p, short o, and t. In these words, o is the middle vowel. Pay attention to the last spelling as well as the first.',['pot','hot','mop','dog'],['p · o · t','h · o · t','m · o · p','d · o · g'],[
 ['Change the p in pot to h. Which word appears?',['hop','hot','hat'],1,'Keep o and t, and change the first spelling to h: hot.'],['Which word ends with g?',['mop','pot','dog'],2,'Dog ends with g. Blend d, short o, and g in order.'],['Which word has the same middle vowel letter as pot?',['mop','map','sip'],0,'Mop and pot have o in the middle. Read all the letters to tell them apart.']]],
 [0,'vowels','Five little vowel paths','Compare the five short-vowel spellings in familiar words.','Practise the short-a, short-i, short-u, short-e, and short-o trail lessons first.','Mat, hen, sit, pot, and sun have different middle vowels. Point to the middle spelling, then blend the whole word. A grown-up can model the sounds if you need help.',['mat','hen','sit','pot','sun'],['m · a · t','h · e · n','s · i · t','p · o · t','s · u · n'],[
 ['Which pair has the same middle vowel letter?',['hen and sit','mat and pot','sun and cup'],2,'Sun and cup both use u. Blend both words and listen for short u.'],['Change the e in pet to o. Which word do you build?',['pot','pat','pit'],0,'Keep p and t. Change the middle vowel from e to o to build pot.'],['Which pair uses two different middle vowels?',['pot and mop','hen and sun','mat and tap'],1,'Hen uses e and sun uses u. The other pairs keep the same middle vowel.']]]
);
const lessons=rows.map(([grade,key,title,objective,prerequisite,pattern,words,parts,checks],index)=>{
 const questions=checks.map(([question,options,answer,explanation])=>({question,options,answer,explanation}));
 return {id:`literacy-pilot-${grade}-${key}`,subject:'reading',grade,kind:'phonics',title,objective,standard:null,minutes:8,order:200+index,pilot:true,prerequisite,reviewStatus:'educator-review-needed',questions,phonics:{title,objective,pattern,words,parts,question:questions[0].question,contrast:questions[0].options,answer:questions[0].answer},parentPractice:'After the on-screen checks, cover the word and ask your child to say it, then build or write it. Model it again if needed. These oral and paper activities are not automatically scored.'};
});
const passages={
 it:{title:'Pip and the kit',sentences:['Pip has a kit.','A pin is in it.','Pip can sit.'],newWords:['Pip','has','is','in','it','can'],helperWords:['a'],note:'Introduce Pip as a name. Model a and the z sound for s in has and is. Blend in, it and can before reading. A kit holds things for a task.',check:['What is in the kit?',['A cup','A pin','A map'],1,'The second sentence says a pin is in it. It means the kit.']},
 mix:{title:'A cup on the mat',sentences:['Pip has a mat.','A cup is on it.','Pip can sit on a mat.'],newWords:['Pip','has','is','on','it','can'],helperWords:['a'],note:'Introduce Pip as a name. Model a and s as z in has and is. Blend on, it and can. In the second sentence, it refers to the mat.',check:['Where is the cup?',['On a mat','In a bus','On a pot'],0,'The second sentence says the cup is on it. The first sentence tells us it is a mat.']},
 compare:{title:'A shop by the pond',sentences:['Pip has a shop.','A shop is at a pond.','Pip can stop and chat.'],newWords:['Pip','has','is','at','can','and'],helperWords:['a'],note:'Introduce Pip as a name. Model a and s as z in has and is. Blend at, can and and. Keep both sounds at the end of and and at the beginning of stop.',check:['Which two things can Pip do?',['Stop and chat','Hop and run','Sit and sip'],0,'The final sentence says Pip can stop and chat. Point to both actions.']},
 sun:{title:'A bug in the sun',sentences:['A bug is in a cup.','A bug is on a cup.','A bug is in the sun.'],newWords:['is','in','on'],helperWords:['a','the'],note:'Model a and the. In is, s represents the z sound. Practise in and on before reading. Trace the words in order.',check:['Where is the bug in the last sentence?',['In the sun','In a bus','On a mat'],0,'The last sentence places the bug in the sun. Find sun in the text.']},
 chin:{title:'A chat at lunch',sentences:['Pip has a chop.','Pip can chat.','Pip has a chat.'],newWords:['Pip','has','can'],helperWords:['a'],note:'Introduce Pip as a name and model a. In has, s represents the z sound. A chop here is a piece of food. Blend can before reading.',check:['What can Pip do?',['Run','Chat','Hop'],1,'The second sentence says Pip can chat. Point to chat.']},
 stop:{title:'A plan by the pond',sentences:['Pip has a plan.','Pip can stop.','Pip can stop at a pond.'],newWords:['Pip','has','can','at'],helperWords:['a'],note:'Introduce Pip as a name and model a. In has, s represents the z sound. Practise can and at. Keep both consonant sounds in st and nd.',check:['Where can Pip stop?',['At a shop','At a tent','At a pond'],2,'The final sentence says Pip can stop at a pond. Point to pond.']},
 map:{title:'Sam and the mat',sentences:['Sam sat.','Sam sat at a mat.','Sam taps a map.'],newWords:['Sam','at','taps'],helperWords:['a'],note:'Introduce Sam as a name. Blend at. In taps, keep both ending sounds, p and s. A grown-up models the helper word a.',check:['What does Sam tap?',['A map','A pot','A pen'],0,'The last sentence says Sam taps a map. Point to map in the text.']},
 hen:{title:'Hen and Ben',sentences:['Ben has a hen.','A hen has a pen.','Ben gets a pet.'],newWords:['Ben','has','gets'],helperWords:['a'],note:'Introduce Ben as a name. In has, s represents the z sound. In gets, keep both ending sounds, t and s. Here, a pen is an enclosure for an animal.',check:['Which animal does Ben have?',['A dog','A hen','A cat'],1,'The first sentence says Ben has a hen. Read that sentence again to check.']},
 pot:{title:'A pot for Pip',sentences:['Pip has a pot.','Pip taps a pot.','A dog sits.'],newWords:['Pip','has','taps','sits'],helperWords:['a'],note:'Introduce Pip as a name. In has, s represents the z sound. Keep both final consonant sounds in taps and sits. A grown-up models a.',check:['Who taps a pot?',['A dog','Sam','Pip'],2,'The second sentence says Pip taps a pot. Find Pip at the start of that sentence.']},
 ship:{title:'Fish at the shop',sentences:['A fish swims.','A fish swims in a shop.','A ship is at a shop.'],newWords:['swims','in','is','at'],helperWords:['a'],note:'Practise swims with a grown-up: s, w, short i, m, z. In is and swims, s can represent the z sound. A grown-up models a. This is an imagined shop with a fish tank and a model ship.',check:['Where does the fish swim?',['In a pond','In a shop','In a cup'],1,'The second sentence says the fish swims in a shop. Return to the text to find the answer.']}
};
for(const [key,p] of Object.entries(passages)){
 const lesson=lessons.find(l=>l.id.endsWith('-'+key));
 const [question,options,answer,explanation]=p.check;
 lesson.phonics.connected={title:p.title,sentences:p.sentences,newWords:p.newWords,helperWords:p.helperWords,note:p.note};
 lesson.questions.push({question,options,answer,explanation});
}
root.WonderCurriculum.lessons.push(...lessons);
root.WonderLiteracy={lessons};
})(globalThis);
