(function(root){
'use strict';
function create(grade){return{grade,round:0,sides:[],solved:false,done:false,message:'Tap a counter to move it to the other basket.'};}
function task(state){const totals=state.grade===0?[3,4,5,6,7]:[6,8,10,12,14];const total=totals[state.round];return{total,left:state.round+1,right:total-state.round-1};}
function prepare(state){state.sides=Array(task(state).total).fill(0);state.solved=false;state.message='Tap a counter to move it to the other basket.';}
function move(state,id){if(state.done||state.solved||!Number.isInteger(id)||id<0||id>=state.sides.length)return false;state.sides[id]=1-state.sides[id];state.message='The counters moved, but the whole stayed the same. Count each basket.';return true;}
function check(state){if(state.done||state.solved)return state.solved;const t=task(state),left=state.sides.filter(n=>n===0).length;state.solved=left===t.left;state.message=state.solved?`You made two parts: ${t.left} + ${t.right} = ${t.total}. Together they still make ${t.total}.`:`You have ${left} in the first basket. We need ${t.left}. Move ${Math.abs(left-t.left)} ${Math.abs(left-t.left)===1?'counter':'counters'} ${left>t.left?'to the second basket':'back to the first basket'}.`;return state.solved;}
function next(state){if(!state.solved||state.done)return false;if(state.round===4){state.done=true;return true;}state.round++;prepare(state);return true;}
function stories(grade){return grade===0?[
 {prompt:'Pip puts 2 shells in a basket, then adds 3 more. How many shells are in the basket?',answer:5,options:[4,5,6],hint:'Start with 2. Count on three times: 3, 4, 5.',equation:'2 + 3 = 5'},
 {prompt:'There are 5 toy boats. Pip puts 2 away. How many toy boats are still out?',answer:3,options:[2,7,3],hint:'Start with five counters. Move two away, then count the counters left.',equation:'5 − 2 = 3'},
 {prompt:'Pip needs 6 blocks. There are 4 on the mat. How many more blocks does Pip need?',answer:2,options:[2,4,10],hint:'Count up from 4 to 6. You add one to reach 5 and one more to reach 6.',equation:'4 + 2 = 6'}
 ]:[
 {prompt:'Pip has 7 blue beads and gets 5 yellow beads. How many beads does Pip have altogether?',answer:12,options:[11,12,13],hint:'Split 5 into 3 and 2. Add 3 to 7 to make 10, then add 2.',equation:'7 + 5 = 12'},
 {prompt:'There are 13 pencils. Pip gives 4 to a friend. How many pencils does Pip keep?',answer:9,options:[8,17,9],hint:'Take 3 from 13 to reach 10. Take away 1 more, because 4 is 3 and 1.',equation:'13 − 4 = 9'},
 {prompt:'Pip wants 14 tiles for a path. There are 8 tiles ready. How many more tiles are needed?',answer:6,options:[6,8,22],hint:'From 8, add 2 to reach 10 and 4 more to reach 14. Combine 2 and 4.',equation:'8 + 6 = 14'}
 ];}
function startStories(s){if(!s.done||s.story)return false;s.story={index:0,attempts:0,assisted:false,solved:false,finished:false,results:[],message:'Try it yourself. You can ask for a hint whenever you need one.'};return true;}
function storyHint(s){const r=s.story;if(!r||r.finished||r.solved)return false;r.assisted=true;r.message=stories(s.grade)[r.index].hint;return true;}
function storyAnswer(s,value){const r=s.story;if(!r||r.finished||r.solved)return false;const q=stories(s.grade)[r.index];if(!q.options.includes(value))return false;r.attempts++;if(value!==q.answer){r.assisted=true;r.message='Not quite yet. '+q.hint;return false;}r.solved=true;r.results.push({firstTry:r.attempts===1&&!r.assisted,attempts:r.attempts});r.message='You worked it out: '+q.equation+'.';return true;}
function storyNext(s){const r=s.story;if(!r||!r.solved||r.finished)return false;if(r.index===2){r.finished=true;return true;}r.index++;r.attempts=0;r.assisted=false;r.solved=false;r.message='Read the story and choose your answer.';return true;}
function storyContent(s){const r=s.story;if(r.finished)return `<h2>You explored three math stories!</h2><p>${r.results.filter(x=>x.firstTry).length} of 3 answered correctly on the first try without a hint this visit.</p><p>Hints and retries help you learn. These few practice questions are not a mastery score.</p><p>With a grown-up, tell a new adding or taking-away story using toy blocks.</p><button class="primary" type="button" data-number-action="restart">Explore again</button><p class="small-print">This visit’s results are not saved.</p>`;const q=stories(s.grade)[r.index];return `<div class="lesson-kicker">STORY ${r.index+1} OF 3 · YOUR TURN</div><h2>Think about Pip’s story</h2><p class="garden-question">${q.prompt}</p><button class="secondary" type="button" data-read-word="${q.prompt}">Hear the story</button><div class="garden-answers">${q.options.map(n=>`<button class="secondary" type="button" data-story-answer="${n}" ${r.solved?'disabled':''}>${n}</button>`).join('')}</div><p class="number-feedback" role="status">${r.message}</p><div class="lesson-actions"><button class="secondary" type="button" data-number-action="hint" ${r.solved?'disabled':''}>Give me a hint</button>${r.solved?'<button class="primary" type="button" data-number-action="story-next">'+(r.index===2?'Finish stories':'Next story →')+'</button>':''}</div><p class="small-print">Optional hints are available. Results describe this visit only.</p>`;}
let active;
function content(s){if(s.story)return storyContent(s);if(s.done)return `<h2>You made five number bonds!</h2><button class="primary" type="button" data-number-action="stories">Try three math stories →</button><p>You split a whole into two parts without changing how many counters there were.</p><p>Try it away from the screen: with a grown-up, split six large toy blocks into two groups. Find another way to split the same six.</p><button class="primary" type="button" data-number-action="restart">Explore again</button><p class="small-print">This guided activity is not a mastery test. This visit’s basket arrangements are not saved.</p>`;const t=task(s),counts=[s.sides.filter(n=>n===0).length,s.sides.filter(n=>n===1).length];return `<div class="lesson-kicker">BUILD ${s.round+1} OF 5 · TAKE YOUR TIME</div><h2>Make ${t.total} in two parts</h2><p>Put <strong>${t.left}</strong> in the first basket and <strong>${t.right}</strong> in the second. Tap a counter to move it.</p><div class="number-baskets">${counts.map((count,side)=>`<section class="number-basket"><h3>${side===0?'First':'Second'} basket · ${count}</h3><div class="number-counters" aria-label="${side===0?'First':'Second'} basket">${s.sides.map((where,id)=>where===side?`<button type="button" class="number-counter" data-counter="${id}" ${s.solved?'disabled':''} aria-label="Move counter ${id+1} to the ${side===0?'second':'first'} basket">●</button>`:'').join('')||'<span class="empty-basket">Empty · zero counters</span>'}</div></section>`).join('')}</div><p class="number-equation" aria-label="${counts[0]} plus ${counts[1]} equals ${t.total}">${counts[0]} + ${counts[1]} = ${t.total}</p><p class="number-feedback" role="status">${s.message}</p><div class="lesson-actions"><button class="primary" type="button" data-number-action="check" ${s.solved?'disabled':''}>Check with Pip</button><button class="secondary" type="button" data-number-action="reset">Start this build again</button>${s.solved?'<button class="primary" type="button" data-number-action="next">'+(s.round===4?'Finish exploring':'Next build →')+'</button>':''}</div><p class="small-print">Guided practice · progress in this activity stays only for this visit.</p>`;}
function render(grade){active=create(grade);prepare(active);return '<section class="panel number-lab" id="number-lab">'+content(active)+'</section>';}
if(root.document)document.addEventListener('click',e=>{const button=e.target.closest('button'),slot=button?.closest('#number-lab');if(!slot||!active)return;let changed=false;const id=Number(button.dataset.counter);if(button.dataset.storyAnswer!==undefined){storyAnswer(active,Number(button.dataset.storyAnswer));changed=true;}else if(button.dataset.counter!==undefined)changed=move(active,id);else switch(button.dataset.numberAction){case'stories':changed=startStories(active);break;case'hint':changed=storyHint(active);break;case'story-next':changed=storyNext(active);break;case'check':check(active);changed=true;break;case'reset':prepare(active);changed=true;break;case'next':changed=next(active);break;case'restart':active=create(active.grade);prepare(active);changed=true;break;}if(changed){slot.innerHTML=content(active);const focus=button.dataset.counter!==undefined?slot.querySelector(`[data-counter="${id}"]`):slot.querySelector('[data-number-action="story-next"], [data-story-answer], [data-number-action="stories"], [data-number-action="next"], [data-number-action="check"], [data-number-action="restart"]');focus?.focus();}});
root.WonderNumberLab={create,task,prepare,move,check,next,render,stories,startStories,storyHint,storyAnswer,storyNext,storyContent};
})(globalThis);
