(function(root){
'use strict';
function create(grade){return{grade,round:0,sides:[],solved:false,done:false,message:'Tap a counter to move it to the other basket.'};}
function task(state){const totals=state.grade===0?[3,4,5,6,7]:[6,8,10,12,14];const total=totals[state.round];return{total,left:state.round+1,right:total-state.round-1};}
function prepare(state){state.sides=Array(task(state).total).fill(0);state.solved=false;state.message='Tap a counter to move it to the other basket.';}
function move(state,id){if(state.done||state.solved||!Number.isInteger(id)||id<0||id>=state.sides.length)return false;state.sides[id]=1-state.sides[id];state.message='The counters moved, but the whole stayed the same. Count each basket.';return true;}
function check(state){if(state.done||state.solved)return state.solved;const t=task(state),left=state.sides.filter(n=>n===0).length;state.solved=left===t.left;state.message=state.solved?`You made two parts: ${t.left} + ${t.right} = ${t.total}. Together they still make ${t.total}.`:`You have ${left} in the first basket. We need ${t.left}. Move ${Math.abs(left-t.left)} ${Math.abs(left-t.left)===1?'counter':'counters'} ${left>t.left?'to the second basket':'back to the first basket'}.`;return state.solved;}
function next(state){if(!state.solved||state.done)return false;if(state.round===4){state.done=true;return true;}state.round++;prepare(state);return true;}
let active;
function content(s){if(s.done)return `<h2>You made five number bonds!</h2><p>You split a whole into two parts without changing how many counters there were.</p><p>Try it away from the screen: with a grown-up, split six large toy blocks into two groups. Find another way to split the same six.</p><button class="primary" type="button" data-number-action="restart">Explore again</button><p class="small-print">This guided activity is not a mastery test. This visit’s basket arrangements are not saved.</p>`;const t=task(s),counts=[s.sides.filter(n=>n===0).length,s.sides.filter(n=>n===1).length];return `<div class="lesson-kicker">BUILD ${s.round+1} OF 5 · TAKE YOUR TIME</div><h2>Make ${t.total} in two parts</h2><p>Put <strong>${t.left}</strong> in the first basket and <strong>${t.right}</strong> in the second. Tap a counter to move it.</p><div class="number-baskets">${counts.map((count,side)=>`<section class="number-basket"><h3>${side===0?'First':'Second'} basket · ${count}</h3><div class="number-counters" aria-label="${side===0?'First':'Second'} basket">${s.sides.map((where,id)=>where===side?`<button type="button" class="number-counter" data-counter="${id}" ${s.solved?'disabled':''} aria-label="Move counter ${id+1} to the ${side===0?'second':'first'} basket">●</button>`:'').join('')||'<span class="empty-basket">Empty · zero counters</span>'}</div></section>`).join('')}</div><p class="number-equation" aria-label="${counts[0]} plus ${counts[1]} equals ${t.total}">${counts[0]} + ${counts[1]} = ${t.total}</p><p class="number-feedback" role="status">${s.message}</p><div class="lesson-actions"><button class="primary" type="button" data-number-action="check" ${s.solved?'disabled':''}>Check with Pip</button><button class="secondary" type="button" data-number-action="reset">Start this build again</button>${s.solved?'<button class="primary" type="button" data-number-action="next">'+(s.round===4?'Finish exploring':'Next build →')+'</button>':''}</div><p class="small-print">Guided practice · progress in this activity stays only for this visit.</p>`;}
function render(grade){active=create(grade);prepare(active);return '<section class="panel number-lab" id="number-lab">'+content(active)+'</section>';}
if(root.document)document.addEventListener('click',e=>{const button=e.target.closest('button'),slot=button?.closest('#number-lab');if(!slot||!active)return;let changed=false;const id=Number(button.dataset.counter);if(button.dataset.counter!==undefined)changed=move(active,id);else switch(button.dataset.numberAction){case'check':check(active);changed=true;break;case'reset':prepare(active);changed=true;break;case'next':changed=next(active);break;case'restart':active=create(active.grade);prepare(active);changed=true;break;}if(changed){slot.innerHTML=content(active);const focus=button.dataset.counter!==undefined?slot.querySelector(`[data-counter="${id}"]`):slot.querySelector('[data-number-action="next"], [data-number-action="check"], [data-number-action="restart"]');focus?.focus();}});
root.WonderNumberLab={create,task,prepare,move,check,next,render};
})(globalThis);
