(function(root){
'use strict';
let mode='words',grade=0,seed=0,answered=false,feedback='',open=[],matched=[],cards=[];
const modes=[['words','Word detective'],['numbers','Number trails'],['math','Math mysteries'],['memory','Matching pairs']];
const original=root.WonderPlay.render;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function challenge(g,n,type){let answer,prompt,hint,options;
if(type==='numbers'){const step=g===0?1:g===1?2:g===2?5:g===3?3:g===4?7:g===5?0.5:1.5,start=g===6?-6+n%4:n%6;const seq=Array.from({length:5},(_,i)=>start+i*step);answer=seq[3];prompt=seq.map((x,i)=>i===3?'?':x).join(' → ');hint=`Each number increases by ${step}. Start at ${seq[2]} and add ${step}.`;options=[answer-step,answer,answer+step,answer+2*step];}
else{const a=2+n%(g===0?4:8),b=1+(n*3)%(g===0?4:7);if(g<=1){answer=a+b;prompt=`Pip has ${a} blocks and finds ${b} more. How many blocks now?`;hint=`Start with ${a}. Count on ${b} more.`;}else if(g===2){answer=a*10+b+12;prompt=`What is ${a*10+b} + 12?`;hint='Add one ten, then add two ones.';}else if(g===3){answer=a*b;prompt=`${a} baskets hold ${b} apples each. How many apples altogether?`;hint=`Use ${a} equal groups of ${b}.`;}else if(g===4){answer=a;prompt=`Share ${a*b} shells equally among ${b} friends. How many does each friend get?`;hint=`Which number multiplied by ${b} makes ${a*b}?`;}else if(g===5){answer=(a+b)/10;prompt=`What is ${(a/10).toFixed(1)} + ${(b/10).toFixed(1)}?`;hint=`Add ${a} tenths and ${b} tenths. Ten tenths make one whole.`;}else{answer=a*3;prompt=`A recipe needs ${a} cups of water per batch. How many cups for 3 batches?`;hint='Multiply the cups for one batch by three.';}const delta=g===5?.1:1;options=[answer,answer+delta,answer+2*delta,answer+3*delta].map(x=>Math.round(x*10)/10);}
const rotate=n%4;options=options.slice(rotate).concat(options.slice(0,rotate));return{answer,prompt,hint,options};}
function makeCards(){const pairs=grade<2?[['☀','☀'],['🌼','🌼'],['🐢','🐢'],['🚀','🚀'],['🐟','🐟'],['🦋','🦋']]:Array.from({length:6},(_,i)=>{const a=i+2+(seed%3);return grade<4?[`${a} + ${a}`,String(a*2)]:[`${a} × 3`,String(a*3)];});cards=pairs.flatMap((p,id)=>p.map(label=>({id,label})));cards=cards.filter((_,i)=>i%2).reverse().concat(cards.filter((_,i)=>i%2===0));open=[];matched=[];}
function tabs(){return `<div class="garden-tabs" aria-label="Puzzle types">${modes.map(([id,label])=>`<button class="secondary" data-garden-mode="${id}" aria-pressed="${mode===id}">${label}</button>`).join('')}</div>`;}
function board(){if(mode==='words')return original('puzzles',grade);const p=challenge(grade,seed,mode);return `<div class="studio-layout"><section class="puzzle-board"><span class="lesson-kicker">${mode==='memory'?'FIND THE PAIRS':'PUZZLE '+(seed+1)}</span><h2>${modes.find(x=>x[0]===mode)[1]}</h2>${mode==='memory'?`<p>${grade<2?'Find two pictures that match.':'Match each expression with its answer.'} Choose two cards. Select another card to turn an unmatched pair back over.</p><div class="memory-grid">${cards.map((card,i)=>`<button data-memory="${i}" class="memory-card" ${matched.includes(card.id)?'disabled':''} aria-label="${matched.includes(card.id)?'Matched '+esc(card.label):open.includes(i)?esc(card.label):'Hidden card '+(i+1)}">${open.includes(i)||matched.includes(card.id)?esc(card.label):'✦'}</button>`).join('')}</div><p>${matched.length} of 6 pairs found.</p>`:`<p class="garden-question">${esc(p.prompt)}</p><div class="garden-answers">${p.options.map(value=>`<button class="secondary" data-garden-answer="${value}" ${answered?'disabled':''}>${value}</button>`).join('')}</div><button class="secondary" data-garden-hint>A clue from Pip</button>`}<p role="status" class="puzzle-status">${esc(feedback)}</p><button class="primary" data-garden-next ${mode==='memory'?matched.length===6?'':'hidden':answered?'':'hidden'}>Another puzzle →</button></section><aside class="play-guide"><img src="pip.png" alt="Pip"><h2>Take your time.</h2><p>Look for a pattern, try an idea, and explain how you know. Mistakes help us decide what to try next.</p></aside></div>`;}
function render(){return `<div id="garden-root">${tabs()}${board()}</div>`;}
function refresh(){document.getElementById('garden-root').outerHTML=render();}
root.WonderPlay.render=function(which,g){grade=g;if(which!=='puzzles')return original(which,g);answered=false;feedback='';makeCards();return render();};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.gardenMode){mode=b.dataset.gardenMode;answered=false;feedback='';makeCards();refresh();}else if(b.hasAttribute('data-garden-hint')){feedback=challenge(grade,seed,mode).hint;refresh();}else if(b.dataset.gardenAnswer!==undefined&&!answered){const p=challenge(grade,seed,mode);answered=Number(b.dataset.gardenAnswer)===p.answer;feedback=answered?'You worked it out! '+p.hint:'Not quite yet. '+p.hint;refresh();}else if(b.hasAttribute('data-garden-next')){seed++;answered=false;feedback='';makeCards();refresh();}else if(b.dataset.memory!==undefined){const i=Number(b.dataset.memory);if(open.includes(i)||matched.includes(cards[i].id))return;if(open.length===2)open=[];open.push(i);if(open.length===2){if(cards[open[0]].id===cards[i].id){matched.push(cards[i].id);feedback=matched.length===6?'All six pairs found!':'A matching pair!';}else feedback='These do not match. Remember their places and try two more.';}refresh();}});
root.WonderGarden={challenge};
})(globalThis);
