(function(root){
'use strict';
const C=root.WonderCurriculum;
const specs=[
[0,9,'compose-five','Two parts, one whole','Combine two parts to make a whole within five.','K.OA.A.1','Use two colors of large counters. Make two parts, push them together and count the whole. Tell what each part represents before writing an equation with a grown-up.'],
[0,10,'decompose-five','Many ways to make five','Separate a whole within five into two parts and explain the result.','K.OA.A.3','Place five counters in a hoop drawn on paper. Move some to one side without removing any from the hoop. Describe both parts, then find a different split of the same whole.'],
[0,11,'join-five','Who joined the picnic?','Act out joining stories and find the new total within five.','K.OA.A.2','Act out a starting group and a group that arrives. Ask what the question is about, then join and count. Draw the story before labeling it with an equation.'],
[0,12,'remove-five','What stays in the nest?','Act out taking-away stories and find what remains within five.','K.OA.A.2','Build the starting group, move away the objects that leave and circle those remaining. Check by putting the parts back together; the whole should match the starting quantity.'],
[1,9,'make-ten-twenty','Make a ten, then add','Split an addend to make ten when adding within twenty.','1.OA.C.6','Build eight and five on two ten-frames. Move two from the five to fill the first frame; three remain in the second. Explain why moving counters preserves the total.'],
[1,10,'near-doubles','A double and one more','Use doubles to explain sums of equal or neighboring addends within twenty.','1.OA.C.6','Build two equal rows. Add one counter to one row, then explain how the known double helps find the new total. Count all to check if needed.'],
[1,11,'subtract-ten','A stop at ten','Break a subtraction into steps that pass through ten.','1.OA.C.6','Build thirteen counters. To remove five, first remove three to reach ten, then remove the remaining two. Explain why a total of five counters, not eight, was removed.'],
[1,12,'three-addends','Three groups at the garden','Add three quantities within twenty using a helpful pair.','1.OA.A.2','Build three colored groups of four, six and three. Combine four and six first to make ten, then include the three. Check that each group was used exactly once.']
];
const math=specs.map(([grade,week,k1Mode,title,objective,standard,activity])=>({id:`k1-year-m-${grade}-${week}`,grade,week,k1Mode,kind:'math',subject:'maths',title,objective,standard,activity,minutes:12,order:600+grade*20+week,reviewStatus:'educator-review-needed'}));
const previous=C.problem;
C.problem=function(l,seed=0){if(!math.some(x=>x.id===l.id))return previous(l,seed);const k=Math.abs(Math.trunc(seed))%10;let prompt,answer,steps,visual,model;switch(l.k1Mode){
case'compose-five':{const pairs=[[1,1],[1,2],[2,2],[2,3],[0,4],[3,1],[1,4],[0,5],[2,1],[0,0]], [a,b]=pairs[k];answer=a+b;model={a,b};prompt=`One tray holds ${a} counters and another holds ${b}. How many altogether?`;visual={type:'k1-parts',parts:[a,b]};steps=[`The first part is ${a}; the other part is ${b}. Zero names an empty part.`,`Combine the parts and count each counter once.`,`The whole is ${answer}: ${a} + ${b} = ${answer}.`];break;}
case'decompose-five':{const total=3+k%3,a=k%(total+1);answer=total-a;model={total,a};prompt=`${total} counters are the whole. ${a} are in the first part. How many are in the other part?`;visual={type:'k1-hidden-part',total,known:a};steps=[`Start with the whole ${total}; do not add the known part to the whole.`,`Put ${a} counters in the first part and count the remaining part.`,`The other part is ${answer}. Check: ${a} + ${answer} = ${total}.`];break;}
case'join-five':{const pairs=[[2,1],[1,3],[2,3],[0,2],[3,2],[1,1],[0,5],[4,1],[0,0],[2,2]], [a,b]=pairs[k];answer=a+b;model={a,b};prompt=`${a} pretend visitors are at a picnic. ${b} more arrive. How many visitors now?`;visual={type:'k1-parts',parts:[a,b]};steps=[`Build the starting group of ${a} visitors.`,`Join the ${b} visitors who arrive. Count every visitor in the new whole.`,`There are ${answer} visitors now. ${a} + ${b} = ${answer}.`];break;}
case'remove-five':{const [total,removed]=[[5,2],[4,2],[3,2],[3,3],[4,0],[5,1],[2,1],[5,0],[2,2],[5,4]][k];answer=total-removed;model={total,removed};prompt=`There are ${total} pretend eggs in a nest. Pip moves ${removed} to another nest. How many stay in the first nest?`;visual={type:'k1-remove',total,removed};steps=[`The starting whole is ${total}. The crossed counters show the ${removed} moved away.`,`Count only the counters that remain in the first nest.`,`There are ${answer} left. Check: ${answer} + ${removed} = ${total}.`];break;}
case'make-ten-twenty':{const a=6+k%4,b=5+k%5,need=10-a,rest=b-need;answer=a+b;model={a,b,need,rest};prompt=`Pip has ${a} green blocks and ${b} gold blocks. How many blocks altogether?`;visual={type:'k1-add-frames',parts:[a,b]};steps=[`${a} needs ${need} more to make ten.`,`Split ${b} into ${need} and ${rest}. Move ${need} counters to fill the first frame; none are added or lost.`,`Now add 10 + ${rest} = ${answer}. Check that both original groups were counted.`];break;}
case'near-doubles':{const a=4+Math.floor(k/2),b=a+(k%2);answer=a+b;model={a,b};prompt=`One row has ${a} counters. A second row has ${b}. How many altogether?`;visual={type:'k1-parts',parts:[a,b]};steps=[`The double ${a} + ${a} makes ${2*a}.`,b===a?'Both rows are equal, so the double is already the required sum.':`The second row has one more than ${a}. Add one to the double.`,`The total is ${answer}. Check by counting both rows.`];break;}
case'subtract-ten':{const total=11+k%5,first=total-10,remaining=1+k%4,removed=first+remaining;answer=total-removed;model={total,removed,first,remaining};prompt=`${total} paper stars are on a board. Pip removes ${removed}. How many remain?`;visual={type:'k1-remove',total,removed};steps=[`Remove ${first} from ${total} to reach ten.`,`The original removal was ${removed}. Since ${first} are already removed, remove only ${remaining} more.`,`10 − ${remaining} = ${answer}. Check: ${answer} + ${removed} = ${total}.`];break;}
case'three-addends':{const a=2+k%5,b=10-a,c=1+k%6,parts=k%2?[c,a,b]:[a,c,b];answer=a+b+c;model={parts:[...parts]};prompt=`Three garden trays hold ${parts[0]}, ${parts[1]} and ${parts[2]} seeds. How many seeds altogether?`;visual={type:'k1-parts',parts};steps=[`Find a helpful pair: ${a} and ${b} make ten.`,`The third group has ${c}. Include it exactly once.`,`10 + ${c} = ${answer}. Reordering the groups does not change their total.`];break;}
}return{mode:l.k1Mode,prompt,answer,display:String(answer),steps,visual,model,options:null};};
const reviewRows=[
[0,9,'Join the parts',[
['Two counters and three counters make how many altogether?',['4','5','3'],1,'Count both parts once each. Two and three together make five.',{type:'k1-parts',parts:[2,3]}],
['An empty tray and a tray with four counters are combined. How many?',['4','0','5'],0,'The empty part adds no counters. The whole still contains four.'],
['Which drawing would show 1 + 2?',['Two groups of two','A group of five only','A part of one and a part of two'],2,'One and two are the parts named by the expression. Together they make three.']]],
[0,10,'Take the whole apart',[
['Five is the whole. One part has two. How many in the other part?',['2','3','5'],1,'Five counters split into two and three. Check by joining the parts.'],
['Which is another way to split four?',['One and three','Four and four','Three and two'],0,'One plus three makes four. The other choices make larger wholes.'],
['All five counters move to one part. How many in the empty part?',['1','5','0'],2,'There are none in the other part, so its quantity is zero. Five and zero still make five.']]],
[0,11,'Picnic stories',[
['Two visitors wait. Two more arrive. How many now?',['2','3','4'],2,'The starting two and arriving two join to make four.'],
['A story begins with one visitor and ends with four after three arrive. Which is the starting group?',['1','3','4'],0,'One is present before the three arrive. Four is the final whole.'],
['No visitors are present. Three arrive. How many now?',['0','3','4'],1,'Starting with zero and joining three makes a whole of three.']]],
[0,12,'What remains?',[
['Five counters are present. Two are moved away. How many stay?',['2','3','5'],1,'Count only the three counters not crossed out.',{type:'k1-remove',total:5,removed:2}],
['Three counters are present and all three leave. How many remain?',['0','3','6'],0,'All three left; none remain. Zero describes the empty group.'],
['Which addition checks 4 − 1 = 3?',['4 + 1 = 5','3 + 3 = 6','3 + 1 = 4'],2,'The remaining three and removed one recreate the starting four.']]],
[1,9,'Make-ten check',[
['To solve 8 + 5, split the five into which parts to fill eight up to ten?',['2 and 3','4 and 1','5 and 5'],0,'Eight needs two; the five splits into two and three. Then ten plus three is thirteen.'],
['9 + 6 becomes 10 + 5. What is the total?',['14','15','16'],1,'One moves from the six to complete ten. Five remain, so the whole is fifteen.'],
['Why does moving counters between frames keep the answer the same?',['Their color changes the sum','Empty spaces count too','No counters are added or removed'],2,'Rearranging the same counters preserves the whole quantity.']]],
[1,10,'Doubles and neighbors',[
['Six plus six is twelve. What is six plus seven?',['12','13','14'],1,'Seven is one more than six, so this sum is one more than the double: thirteen.'],
['Which double helps with 4 + 5?',['4 + 4','5 + 7','3 + 6'],0,'Four plus four is eight. The extra one in five makes nine.'],
['Two rows each contain eight counters. What is their total?',['8','15','16'],2,'Eight plus eight is sixteen. Both equal groups must be counted.']]],
[1,11,'Subtract through ten',[
['For 13 − 5, remove three to reach ten. How many more must be removed?',['5','3','2'],2,'The five being removed splits into three and two. Only two remain to remove after reaching ten.'],
['12 − 4 becomes 10 − 2. What remains?',['8','6','10'],0,'Two were removed to reach ten, and two more gives eight. Four were removed altogether.'],
['How can you check 14 − 6 = 8?',['14 + 6 = 20','8 + 6 = 14','8 − 6 = 2'],1,'Joining the remainder and removed part should recreate the original whole fourteen.']]],
[1,12,'Three groups, one total',[
['Which pair is helpful in 3 + 4 + 6?',['3 and 4','4 and 6','3 and 6'],1,'Four and six make ten; then include the three to make thirteen.'],
['What is 7 + 2 + 3?',['10','11','12'],2,'Seven and three make ten, with two still to include. The total is twelve.'],
['Pip rearranges 5 + 1 + 5 as 5 + 5 + 1. Why is this allowed?',['The same three parts are each included once','The one can be ignored','Reordering always adds one'],0,'Changing the grouping or order does not change the sum when all original parts are included exactly once.']]]
];
const reviews=reviewRows.map(([grade,week,title,rows])=>{const source=math.find(l=>l.grade===grade&&l.week===week),questions=rows.map(([question,options,answer,explanation,visual])=>({question,options,answer,explanation,...(visual?{visual}:{})}));return{id:`k1-review-${grade}-${week}`,grade,week,title,subject:'maths',kind:'inquiry',k1Review:true,objective:source.objective,standard:source.standard,teach:source.activity+' Use models and explain each quantity. These checks help choose further practice; they do not certify mastery.',activity:'Invent a fresh example with large counters and explain it to a grown-up. Revisit one earlier strategy and compare how it helps.',questions,...questions[0],minutes:10,order:650+grade*20+week,reviewStatus:'educator-review-needed'};});
function dots(n){return n?Array.from({length:n},()=>'<i aria-hidden="true"></i>').join(''):'<span>Empty part</span>';}
function visual(v){if(v.type==='k1-parts')return '<div class="k1-parts" role="img" aria-label="Groups containing '+v.parts.join(', ')+' counters">'+v.parts.map((n,i)=>'<div class="k1-part"><strong>Part '+(i+1)+'</strong><div>'+dots(n)+'</div></div>').join('')+'</div>';if(v.type==='k1-hidden-part')return '<div class="k1-whole"><p>Whole: '+v.total+'</p><div class="k1-parts"><div class="k1-part" role="img" aria-label="Known part: '+v.known+' counters"><strong>Known part</strong><div>'+dots(v.known)+'</div></div><div class="k1-part"><strong>Other part</strong><p aria-label="Unknown number of counters">?</p></div></div></div>';if(v.type==='k1-add-frames')return '<div class="k1-add-frames">'+v.parts.map((n,i)=>'<section><strong>Group '+(i+1)+'</strong>'+root.WonderK1Second.visual({type:'k1-frame',n})+'</section>').join('')+'</div>';if(v.type==='k1-remove')return '<div class="k1-remove" role="img" aria-label="'+v.total+' starting counters; '+v.removed+' are crossed out as removed">'+Array.from({length:v.total},(_,i)=>'<i aria-hidden="true" class="'+(i>=v.total-v.removed?'removed':'')+'">'+(i>=v.total-v.removed?'×':'')+'</i>').join('')+'</div><p class="model-caption">Crossed counters were removed. Count those that remain.</p>';return'';}
C.lessons.push(...math,...reviews);root.WonderK1Third={math,reviews,visual};
})(globalThis);
