(function(root){
'use strict';
function create(parts){const target=parts.split(' · ');const tiles=target.map((text,id)=>({text,id})).reverse();if(tiles.map(t=>t.text).join('')===target.join(''))tiles.push(tiles.shift());return{target,tiles,chosen:[],message:'Choose the tiles in reading order.',correct:false};}
function choose(state,id){if(!Number.isInteger(id)||!state.tiles.some(t=>t.id===id)||state.chosen.includes(id))return false;state.chosen.push(id);state.correct=false;state.message='Keep going, or check your word.';return true;}
function remove(state,id){state.chosen=state.chosen.filter(n=>n!==id);state.correct=false;state.message='Try another tile.';}
function check(state){const picked=state.chosen.map(id=>state.tiles.find(t=>t.id===id).text);state.correct=picked.length===state.target.length&&picked.every((p,i)=>p===state.target[i]);state.message=state.correct?'You built it! Now read the whole word and explain its pattern.':picked.length<state.target.length?'There are still empty spaces. Choose another tile.':'Look from left to right. Tap a placed tile to move it back, then try again.';return state.correct;}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current=null;
function body(state){return `<p class="builder-instruction">Build <strong>${esc(state.target.join(''))}</strong>. Use the spelling pieces shown. Pieces may represent sounds, syllables or meaningful word parts. Tap a placed tile to return it.</p><div class="builder-slots" aria-label="Your word">${state.target.map((_,i)=>{const id=state.chosen[i],tile=state.tiles.find(t=>t.id===id);return tile?`<button type="button" data-tile-remove="${id}" aria-label="Return ${esc(tile.text)} tile">${esc(tile.text)}</button>`:'<span aria-label="Empty space">·</span>';}).join('')}</div><div class="builder-bank" aria-label="Available tiles">${state.tiles.map(t=>`<button type="button" data-tile-add="${t.id}" ${state.chosen.includes(t.id)?'disabled':''} aria-label="Add ${esc(t.text)} tile">${esc(t.text)}</button>`).join('')}</div><div class="lesson-actions"><button type="button" class="primary" id="check-built-word">Check my word</button><button type="button" class="secondary" id="reset-built-word">Start again</button></div><p role="status" class="builder-feedback">${esc(state.message)}</p><small>This is guided practice. It does not score pronunciation or add completion stars.</small>`;}
function markup(parts){current=create(parts);return `<section class="word-builder" id="word-builder" aria-label="Word building practice"><h3>Build it with Pip</h3>${body(current)}</section>`;}
if(root.document)document.addEventListener('click',e=>{const button=e.target.closest('button'),slot=button?.closest('#word-builder');if(!slot||!current)return;let changed=false;if(button.dataset.tileAdd!==undefined)changed=choose(current,Number(button.dataset.tileAdd));else if(button.dataset.tileRemove!==undefined){remove(current,Number(button.dataset.tileRemove));changed=true;}else if(button.id==='check-built-word'){check(current);changed=true;}else if(button.id==='reset-built-word'){current=create(current.target.join(' · '));changed=true;}if(changed){slot.innerHTML='<h3>Build it with Pip</h3>'+body(current);slot.querySelector('#check-built-word')?.focus();}});
root.WonderWordBuilder={create,choose,remove,check,markup};
})(globalThis);
