(function(root){
'use strict';
const C=root.WonderCurriculum,Y=root.WonderYear;
const science=[
['Sort by properties','2-PS1-1','A material has properties we can observe, such as texture, flexibility, and whether light passes through it. We can sort the same objects in different ways. A clear plastic lid can be smooth and transparent; those are two different properties.','Which describes a material property?',['Smooth','Lucky','Friendly'],0,'Smooth describes a surface we can observe.','With a grown-up, sort six safe objects by texture, then by flexibility. Draw both groups. Do not taste materials.'],
['Choose the right material','2-PS1-2','A useful material depends on the job. A towel should absorb water, while a rain cover should resist it. To compare materials fairly, use equal-sized pieces and equal amounts of water. Record what happens instead of picking a favorite first.','What should stay the same in a water test?',['The amount of water','The observed result','The material being compared'],0,'Keeping the water amount the same helps compare the materials.','Test a small drop of water on equal pieces of paper towel and foil in a tray. Record which absorbs it. Dry the area afterward.'],
['Same pieces, new object','2-PS1-3','Small pieces can be used to build different objects. Six blocks can form a wall, then a tower. The arrangement changes, but the same blocks remain. A drawing before and after rebuilding can show what changed and what stayed the same.','What stays the same when the same six blocks are rearranged?',['Their arrangement','The number of blocks','The shape of the building'],1,'Rearranging the blocks does not add or remove blocks.','Build two different models with the same six large blocks. Draw them and count the pieces each time.'],
['Changes we can reverse','2-PS1-4','Warming can melt ice into liquid water. Cooling that water enough can freeze it again. Other changes, such as baking dough, are not easily reversed. We use observations to describe whether a material can return to its earlier form under the conditions tested.','Which change can be reversed by cooling?',['Ice melting','Paper burning','Dough baking'],0,'Liquid water can freeze back into ice.','Observe an ice cube melting in a bowl. Ask a grown-up to freeze the water again. Compare drawings. No heating equipment is needed.'],
['A fair plant investigation','2-LS2-1','Plants need suitable conditions to grow. To investigate water or light, compare plants while changing one condition at a time. Keep the kind of plant, container, and observation times alike. Record growth over several days and avoid drawing a conclusion from one glance.','What makes a comparison easier to interpret?',['Changing one condition at a time','Changing every condition','Measuring only one plant'],0,'One changed condition makes it easier to connect results to that condition.','Plan a comparison with a grown-up using two similar plants. Choose water or light as the variable. Predict, record over time, and restore suitable care after a brief test.'],
['Seeds on the move','2-LS2-2','Plants can spread seeds in different ways. Some seeds catch the wind. Some attach to an animal’s fur, and some are carried after animals eat fruit. A model can show how shape helps a seed move, even though it is not a real seed.','Which feature could help a seed catch on fur?',['Small hooks','A square label','A loud sound'],0,'Hook-like structures can catch on fur or fabric.','Design a paper seed that moves in gently moving air. Compare two shapes on a clear table. Do not release materials outdoors.'],
['Pollination partners','2-LS2-2','When some animals visit flowers, pollen can move with them to another flower. This can help certain plants produce seeds. Not every flower depends on an animal; wind also moves pollen for some plants. A model can represent one part of this process.','What can an animal move between flowers?',['Pollen','Rocks','Roots'],0,'Pollen can cling to an animal visiting flowers and be carried onward.','Use two paper flowers and a paper bee. Move removable paper dots to model pollen transfer. Explain what the model shows and what it leaves out.'],
['Life in two places','2-LS4-1','Different habitats can support different living things. A shaded patch and a sunny patch may have different plants and animals. Observe both places for the same length of time. A list tells what you saw, not every organism that could ever live there.','What makes the observation time fairer?',['Equal time in both places','One minute here and one hour there','Only looking where you expect animals'],0,'Equal observation time reduces one difference in how the places are studied.','With an adult, observe two safe outdoor patches without touching wildlife. List plants and animals seen. Compare the lists and discuss what may have been missed.'],
['Many kinds of living things','2-LS4-1','A pond, woodland, and grassland can contain different kinds of plants and animals. Even one habitat can contain variety. Use observations or reliable photographs to compare living things. Color alone may not tell you whether two organisms are the same kind.','Which is evidence of variety in a habitat?',['Observing several kinds of plants','Assuming everything is identical','Counting only stones'],0,'Several kinds of plants are one sign of biological variety.','Use an adult-selected field guide or nature photographs. Draw three organisms from one habitat and label an observable difference.'],
['Fast and slow Earth changes','2-ESS1-1','Earth’s surface changes at different speeds. A landslide can move material quickly. Weathering can break rock down over a long time. Pictures taken at different times help people study changes that are too slow or too dangerous to watch closely.','Which can happen quickly?',['A landslide','Every mountain forming in a day','All rock becoming sand instantly'],0,'A landslide may move material rapidly.','Compare adult-selected before-and-after photographs of a landscape. Describe a change and the evidence for its timing. Never visit unstable slopes.'],
['Water moves soil','2-ESS2-1','Flowing water can move loose soil. Plants, barriers, and other designs may reduce how much soil moves. Engineers compare solutions using similar slopes and equal water amounts. A small model helps test ideas but does not reproduce every outdoor condition.','Why use equal water amounts when testing barriers?',['To compare the barriers more fairly','To make every result equal','To avoid making observations'],0,'Different water amounts could change erosion even if the barriers were the same.','In a tray with a grown-up, compare gentle water flow over two small sand slopes, one with a paper barrier. Use equal water amounts. Keep sand out of drains.'],
['Land and water models','2-ESS2-2','Maps and models represent the shapes and kinds of land and water in an area. A model might show a hill, a river, and a lake. It is smaller than the real place and leaves out details. Labels and a key help people understand it.','What should a model of an area represent?',['Important land and water features','Every grain of soil','Only favorite colors'],0,'Models select features that help answer a question about the area.','Make a paper map of an imaginary area with a hill, river, and lake. Add labels and a key. Explain one limit of your map.'],
['Where water is found','2-ESS2-3','Water is found in oceans, rivers, lakes, and underground. It also occurs as ice in cold places and as water vapor in air. Most water on Earth is salty ocean water. Pictures and reliable books help us investigate places we cannot visit.','Which is frozen water?',['Glacier ice','Dry sand','A stone'],0,'A glacier is a large body of ice formed on land.','Use an atlas or adult-selected photographs to find liquid water and ice. Make a two-column chart with examples and their sources.'],
['Ask an engineering question','K-2-ETS1-1','An engineering problem begins with a need. A toy figure keeps falling from a shelf. Before designing, ask what the holder must do and which materials are available. Requirements describe success; limits include size, materials, or time.','Which is a requirement for a toy holder?',['It must keep the toy upright','It must be your favorite color always','It must use unlimited materials'],0,'Keeping the toy upright describes what the holder needs to do.','Choose a small classroom or home problem with a grown-up. Write the need, two success requirements, and available safe materials.'],
['Sketch before building','K-2-ETS1-2','A sketch can show how a proposed object will work. Labels identify parts, and arrows can show movement. A model lets people examine an idea before making a larger version. A model is useful even when it does not include every detail.','Why label a design sketch?',['To explain the parts','To hide the idea','To avoid thinking about its purpose'],0,'Labels help others understand the parts and their roles.','Sketch a paper stand for a card. Label its base and support. Build a small model using paper and folded tabs. Ask an adult before using scissors.'],
['Test two designs','K-2-ETS1-3','To compare two designs, decide what success means before testing. Use the same load and surface for two paper stands. Repeat the test and record results. A design that works once may need more testing before a strong conclusion is possible.','What should be the same in both stand tests?',['The card being held','The design itself','The result'],0,'Using the same card helps compare the two different stands.','Test two paper stands with the same card three times. Record whether each stays upright. Change one feature and test again.'],
['An explanation with evidence','2-PS1-2; K-2-ETS1-3','A claim says what you think the results show. Evidence describes observations or measurements. Reasoning connects them. If one paper stand held a card in all three trials and another fell twice, the results support a limited claim about those stands in that test.','Which sentence gives evidence?',['Stand A held the card in three trials','Stand A is magical','Everyone must like Stand A'],0,'A count from the test is evidence that can be checked.','Use your test notes to write a claim, two observations, and one limit. Explain what you would test next.'],
['Share an investigation','K-2-ETS1-3; 2-LS4-1','A useful investigation report includes the question, method, observations, and what the evidence suggests. It also names questions that remain. Sharing a report lets other people ask for details and compare ideas. Changing an explanation when evidence changes is part of learning.','What belongs in an investigation report?',['Question, method, observations, and explanation','Only a favorite answer','Only a picture without labels'],0,'These parts let another person understand and discuss the investigation.','Choose a safe investigation from this year. Make a display with your question, labeled drawing or table, conclusion, and a next question.']
];
const social=[
['Our communities','history','A community is a group connected by a place, activity, or shared purpose. People can belong to several communities. A school community includes learners and people with many roles. Learning about those roles helps us understand how people depend on one another.','Which is an example of a community?',['People working together at a school','One empty pencil case','A single cloud'],0,'A school connects people through shared activities and responsibilities.','Draw three communities you belong to. Describe a way people help each other in each.'],
['Then and now','history','Photographs and objects can give clues about life in the past. A picture of an old classroom may show different tools from a classroom today. One picture does not show every classroom or every child’s experience. Compare carefully and ask when and where a source was made.','What should you ask about an old photograph?',['When and where it was made','Whether it knows your name','Whether it shows every place'],0,'Time and place help us interpret the evidence.','With a grown-up, compare an old and recent photograph of the same kind of place. List changes and things that stayed similar.'],
['Put events in order','history','A timeline arranges events in order. Dates or words such as before and after help show sequence. A timeline of a school year could include the first day, a class project, and the last day. It selects events; it does not contain everything that happened.','What does a timeline help show?',['The order of events','The weight of books','Every person’s opinion'],0,'Timelines organize events by time.','Make a timeline of four events from a day or a story. Add before and after sentences. Personal family details are optional.'],
['Listen to a memory','history','A person’s account of something they experienced is one source about the past. Memories can be valuable and can also leave out details. Ask respectful questions, record the person’s words accurately, and compare with other evidence when possible. People can decline to answer.','How should you use a person’s memory?',['As one source to consider','As proof of every detail forever','As something to change without asking'],0,'An account contributes evidence but may need comparison with other sources.','Ask a willing grown-up about a school tool from their childhood. Write one question, their answer, and a follow-up. Do not record private information.'],
['Why communities have rules','history','Rules can help people share spaces and reduce harm. A library may ask visitors to speak quietly so others can read. People can discuss whether a rule is fair and whether it works. An explanation is stronger when it connects a rule to its purpose.','Why might a library have a quiet area?',['To help people concentrate','To stop all reading','To make books heavier'],0,'The rule supports people who need a quiet place to read.','Choose a shared-space rule. Explain its purpose and suggest how to tell whether it helps.'],
['Make a shared decision','history','Groups can listen to ideas, compare reasons, and make a decision. Voting is one method, but a fair process also lets people speak and protects basic needs. If a class chooses a game, it should consider whether everyone can participate.','What should happen before a group chooses?',['Hear ideas and reasons','Ignore anyone who disagrees','Let only the loudest person speak'],0,'Listening helps the group consider different needs and reasons.','With a grown-up or friend, compare two activity choices. Give reasons, decide fairly, and discuss how each person was heard.'],
['Goods and services','history','Goods are things people make or use, such as bread or a chair. Services are work done for others, such as repairing a bicycle. Communities need many kinds of work. Some work is paid, and some is unpaid help at home or in the community.','Which is a service?',['Repairing a bicycle','A loaf of bread','A new notebook'],0,'Repairing is work performed for someone.','List three goods and three services used in a day. Include an example of unpaid help.'],
['Needs, choices, and resources','history','People make choices because time, materials, and money are limited. Needs include things such as food, shelter, and care. Wants can make life enjoyable, but people may need to choose among them. Different situations can change what someone needs.','Why do people sometimes choose between two wants?',['Resources can be limited','All wants are identical','Time never runs out'],0,'Limited resources make choices necessary.','Plan a pretend picnic with a limited list of supplies. Explain two choices without sharing real household finances.'],
['A community changes','history','Communities change as people move, build, work, and share ideas. A new bus route may help some people reach a library. Others may ask about noise or safe crossings. Studying change includes asking who is affected and using evidence from more than one source.','What helps us understand a community change?',['Different people’s experiences and evidence','Only one guess','Ignoring the past'],0,'Several sources help show different effects of a change.','Use public photographs or a grown-up’s account to study a local change. Show before, after, benefits, and questions.'],
['A map of a room','geography','A map represents a place from above. It uses symbols to stand for objects or features. A room map might show tables as rectangles and doors as gaps. The map leaves out details that are not useful for its purpose.','What view does a simple room map usually show?',['A view from above','Only inside a drawer','Every side at once'],0,'A view from above helps show where objects are placed.','Draw an imaginary classroom from above. Include a door, tables, and a key. Do not put your home address on the map.'],
['Symbols and a key','geography','A map key explains symbols. A blue line might stand for a river, and a small square might stand for a building. Always check the key rather than assuming a symbol has the same meaning on every map.','Where can you check what a map symbol means?',['The key','The page number alone','A random story'],0,'The map key explains the symbols used on that map.','Invent three map symbols and a key. Ask someone to identify them using only your key.'],
['Direction words','geography','North, south, east, and west are cardinal directions. On many maps north is at the top, but an arrow or compass rose tells you for sure. Relative directions, such as left, depend on which way a person is facing.','What should you check before finding north on a map?',['Its direction arrow or compass rose','Its brightest color','Its title length'],0,'The arrow or compass rose indicates direction on the map.','Draw a map with a north arrow. Place a pond east of a tree and a hill south of it. Explain a route.'],
['Landforms and water','geography','A landform is a feature of Earth’s land, such as a hill, valley, or plain. Bodies of water include lakes, rivers, and oceans. A river flows along a channel; a lake is surrounded by land. Maps show these features using shapes, colors, and labels.','Which is a body of water surrounded by land?',['A lake','A hill','A valley with no water'],0,'A lake is an inland body of water.','Make a labeled picture with two landforms and two water features. Explain how one differs from another.'],
['Looking at a globe','geography','A globe is a round model of Earth. It shows large land areas and oceans. Earth’s continents are large land regions; countries are areas with political boundaries. A continent and a country are different kinds of regions. A globe is too small to show every local detail.','How is a globe useful?',['It models Earth’s round shape','It shows every house clearly','It predicts every day’s weather'],0,'A globe represents the overall shape and broad features of Earth.','With a grown-up and a labeled globe or atlas, find two continents and two oceans. Compare what a globe and a local map can show.'],
['Weather and places','geography','Weather describes conditions at a place and time, such as rain or temperature. Climate describes patterns over much longer periods. People may plan clothing or buildings for common local conditions, while still checking the day’s weather.','Which describes weather?',['It is raining here today','A place’s usual pattern over many years','The shape of a continent'],0,'Today’s rain describes conditions at a particular time and place.','Keep a five-day weather chart from safe indoor observations. Explain why five days do not describe a place’s whole climate.'],
['People use the land','geography','People use land for homes, farms, parks, roads, and many other purposes. Choices can bring benefits and create problems. A park provides space for play and habitat, while a road connects places. Planning involves considering people, living things, and available space.','What should a land-use plan consider?',['People and environmental effects','Only one favorite color','No one’s needs'],0,'Land choices affect people and other living things.','Design an imaginary neighborhood with homes, a park, a road, and a community building. Explain one trade-off.'],
['Connections between places','geography','Places are connected when people, goods, and ideas move between them. Food may travel from a farm to a market. A book may carry an idea from a writer to readers far away. Maps can help trace a journey, but real routes depend on roads, water, and other conditions.','Which shows a connection between places?',['Food moving from a farm to a market','An empty box staying still','A dot without a label'],0,'The food journey connects where it is grown with where it is sold.','Choose a common object and investigate where it was made using its label with a grown-up. Mark an approximate route on a map.'],
['Our place in the world','geography','A local place belongs to larger regions. A town may be within a state or province and a country. Different countries organize regions in different ways. Maps of different scales answer different questions: a street map helps with a nearby route; a world map shows much larger relationships.','Which map is best for a short route between nearby buildings?',['A local street map','A map showing only continents','A picture of the Moon'],0,'A local map shows details that a world map leaves out.','Create a display with an imaginary local map and a world map reference. Explain what question each can answer.']
];
science.forEach((r,i)=>C.lessons.push({id:`year2-s-${i+1}`,grade:2,subject:'scienceLab',kind:'inquiry',title:r[0],objective:'Investigate, gather evidence, and explain: '+r[0].toLowerCase()+'.',standard:r[1],teach:r[2],question:r[3],options:r[4],answer:r[5],explanation:r[6],activity:r[7],minutes:20,order:100+i}));
social.forEach((r,i)=>C.lessons.push({id:`year2-h-${i+1}`,grade:2,subject:r[1],kind:'inquiry',title:r[0],objective:'Use questions and evidence to explore '+r[0].toLowerCase()+'.',standard:null,teach:r[2],question:r[3],options:r[4],answer:r[5],explanation:r[6],activity:r[7],minutes:20,order:100+i}));
Y.science=science;Y.social=social;
})(typeof globalThis!=='undefined'?globalThis:this);
