(function(root){
'use strict';
const C=root.WonderCurriculum;
// Each additional check targets a different detail, word meaning, inference, or application.
// In each authored row the first option is correct; rotate before presentation.
const reading=[
[['What helped Pam solve the problem?','Remembering where she packed her snack','Walking faster on the trail','Getting a different map','Pam retraced her morning and returned to the bench.'],['What happened before the walk began?','Pam checked the map','Pam lost the map on the trail','Dad left without Pam','The final part says Pam checked the map before setting off.']],
[['Why did Kate wait?','There was not enough wind','The kite needed food','The road needed paint','The wind was too gentle, so Kate waited for a breeze.'],['How are kit and kite different?','The final e changes the vowel sound','They have no letters in common','They mean exactly the same thing','Kite has a silent final e and a long-i sound.']],
[['Which action shows Pip was careful?','Pip left the gate closed','Pip chased the sheep','Pip pulled down the fence','Pip asked the keeper instead of opening the gate.'],['Which word names plants along the stream?','reeds','keepers','gates','The first part describes green reeds beside the water.']],
[['Which word uses ay for long a?','play','rain','train','Play has the ay spelling; rain and train use ai.'],['What changed for May?','Waiting became interesting','The station disappeared','The rain became snow','The word game turned the wait into a discovery.']],
[['What helped the friend understand Jo’s picture?','The caption','A new shovel','The road becoming longer','The friend used the picture and words together.'],['What does scene mean here?','The view Jo drew','A type of coat','A long journey','The scene is the view of snow and the worker outside.']],
[['Why did Ravi make two word groups?','The oo spelling had two sounds','The words had no vowels','Every word meant soup','Book and spoon use the same vowel letters for different sounds.'],['Which belongs with moon?','spoon','book','look','Spoon and moon share the longer oo sound in the model.']],
[['Why could Nora still draw the horse?','The farmer showed a safe viewing place','She climbed into the field','She moved the horse into her house','Following the rule still allowed Nora to watch from beside the fence.'],['Which detail shows where the visit happens?','The farm gate','A train ticket','A beach umbrella','The farm gate and farmer locate the event at a farm.']],
[['What happened after the brother ran toward the bird?','The bird flew away','The bird read a book','The bird built a chair','The passage connects the running approach with the bird flying away.'],['What does patiently mean in this story?','Waiting calmly','Moving as fast as possible','Making a loud noise','Fern and her brother sit still and wait for the bird.']],
[['Why did the puzzle suit Joy’s plan?','It could be shared indoors during short breaks','It needed a deep pool','It could never be stopped','Joy considered rainy days and flexible play.'],['What does prefer mean?','Like one choice more than another','Buy every choice','Forget the choices','A preference selects one option over another for a reason.']],
[['Which detail shows Lou helped safely?','An adult moved the heavier things','Lou carried everything alone','Lou stood outside in the storm','Lou carried a small box while an adult handled heavier things.'],['Which event happened last?','Rain began during the story','Lou checked with the librarian','The books were moved indoors','The last part places the rain after the story hour moved.']],
[['Why did Pip write a question about the string?','Pip had not seen what the robin did next','The string was invisible','Pip knew every bird’s plan','The nest-material idea was an inference, not a directly observed fact.'],['Which is a two-syllable word with a long-a sound?','paper','string','bird','Paper has two syllables; its first vowel is long a.']],
[['What does uneven mean?','Not even','Even again','Very finished','The prefix un- means not in uneven.'],['What did Pip do before hanging the sign?','Reread it','Wash every window','Throw away the smaller brush','The passage says Pip reread the sign before hanging it.']],
[['How are careful and careless different?','They express different amounts of care','They always mean the same thing','They have different base words','Both contain care, but the suffix changes the meaning.'],['Which action supports the word helpful?','Ana offers to carry a small box','Ana hides the boxes','Ana leaves without speaking','Ana offers a specific action that helps her neighbor.']],
[['Why did Dean’s first attempt not fit?','He used the vowel sound from bead','He forgot every letter','The recipe contained no words','Dean first tried the long-e sound from bead in bread.'],['Which word belongs with bread by vowel sound?','head','seed','bead','Head and bread share the short-e vowel sound in these words.']],
[['What information did the teacher ask for?','Where the glove was found','What the children ate','How tall the gate was','The teacher asked for the location of the lost item.'],['What does owner mean?','The person an item belongs to','The place an item is stored','A person who sees every item','The owner came to collect their glove.']],
[['What does the comma help Pip do?','Pause briefly','Change the character’s name','Skip the next word','A small pause helps separate the call from Pip’s name.'],['What was the goal of rereading?','Help the listener understand','Finish faster than everyone','Remove all expression','The passage explicitly values understanding over racing.']],
[['How did Eli check the lunch box belonged to him?','He saw his name on its label','He guessed from the weather','He counted every shelf','The label still showed Eli’s name.'],['What did the classmate suggest?','Check another shelf','Go home without lunch','Buy a green bag','The classmate’s suggestion led to the shelf with the green bag.']],
[['What evidence changed Ben’s mind?','His many trips had watered plants too','His bucket suddenly grew','The others stopped watering','The damp soil and many trips showed his contribution mattered.'],['What does contribution mean here?','Work that helps a shared job','A broken tool','A type of soil','Ben’s watering was part of the group’s work.']],
[['What was wrong with the first tower’s base?','It was narrower than the top','It had too many labels','It was made of clouds','Lena studies the narrow base before widening it.'],['Which describes Lena’s change in approach?','She investigates instead of giving up','She stops noticing the blocks','She asks her friend to disappear','After the break, Lena studies the problem and changes her plan.']],
[['How do patter, tap, and drip help the poem?','They suggest sounds of rain','They list kinds of animals','They give exact temperatures','These sound words help the reader hear the rainy scene.'],['Which response connects to the poem’s rhythm?','Tapping gently while reading','Reading every word silently backward','Ignoring line endings','Pip taps to the rhythm while reading the lines.']],
[['How does the ending connect to the problem?','The toy crosses after the design changes','The toy never reaches the bridge','The story begins at a different river','The ending shows the new design working.'],['Why does Omar draw the changed design?','So he can build it again','So the sticks become heavier','So the river becomes real','The text gives remembering the successful design as the reason.']],
[['Which detail explains the grandfather’s response?','His garden soil was dry','He dislikes every game','He could not hear Tia','The rain helps a garden that needs water.'],['What helps the characters understand each other?','Explaining and listening','Repeating the loudest words','Refusing to discuss plans','Each describes what the rain means for their plans.']],
[['Why was the friend’s first interpretation different?','The picture alone left out whether watering was finished','The friend could not see a plant','The caption named a different child','The empty can could fit more than one explanation.'],['What is a caption?','Words that explain a picture','The handle of a watering can','A kind of seed','Mika adds a short explanation below the drawing.']],
[['What differs between the two stories?','One shares food; the other shares turns','Only one includes children','One takes place on the Moon','The text directly compares the things being shared.'],['Which question would help compare the stories?','How does each group make sharing fair?','Which story has the most letters in its title?','Which page is heavier?','This question focuses on actions connected to the shared theme.']],
[['How are carrot roots and grass roots different?','A carrot root is thick; grass has many thin roots','Grass never has roots','Carrot roots grow only in the sky','The passage contrasts these root forms.'],['How can you study roots without pulling up a plant?','Use a picture or a plant being repotted','Remove every plant nearby','Cover all the leaves','The last part suggests a less damaging observation method.']],
[['What helps the seedling make food after leaves develop?','Light','Paint','Plastic labels','The passage connects leaves and light with making food.'],['What does sequence mean in this lesson?','The order of stages','The weight of the seed','The color of the notebook','First and later organize the growth process in order.']],
[['Where could a reader find the meaning of habitat?','The glossary','Only the Trails heading','The date at the bottom','The passage says the glossary explains unfamiliar words.'],['How does a contents list help?','It points to sections','It replaces every photograph','It measures the park','The contents list helps readers locate relevant information.']],
[['Which detail supports the meaning of damp?','Drops clung to the grass','The path had a name','Pip owned a book','Water drops are evidence that the area was slightly wet.'],['Why did Pip reread after checking the meaning?','To see whether the definition fit the sentence','To make the word disappear','To count every page','Rereading checks the meaning in its context.']],
[['What must readers still do while saving water?','Wash hands thoroughly','Skip soap forever','Never rinse','The notice says saving water does not mean skipping hygiene.'],['Which reason supports the requested action?','It reduces wasted water','It makes the tap larger','It changes the calendar','The notice connects turning off unnecessary flow with less waste.']],
[['Why use the same books in both bags?','To make the comparison fairer','To force identical results','To hide the handles','A different load could affect stretching independently of the bag.'],['What is a limit of the test?','Only two bags and one load were tested','The report used words','The bags had handles','The class cannot generalize the small test to every bag or load.']],
[['Why should Pip avoid saying all bees live in colonies?','The source described only some bees','The page was about rivers','No bee can live near another','A claim should not extend beyond what the source supports.'],['Why use both pages in the report?','They provide different information about the topic','They guarantee every fact about all insects','They eliminate the need to read','The pages complement one another by covering different aspects.']],
[['How do dates help the garden notebook?','They show when observations happened','They make plants grow faster','They replace every drawing','Dates help readers compare growth over time.'],['Which structure fits the report?','Topic, supporting facts, ending','Only a title repeated','Unrelated events without a topic','The final part describes this informational structure.']],
[['Which reason supports choosing a puzzle?','People can return to an unfinished puzzle','Every board game is bad','Puzzles never have pieces','The writer values play that suits shorter breaks.'],['Why may another child choose differently?','Opinions can differ even after reasons are shared','Only one child may think','Reasons make agreement compulsory','The text explains that an opinion is not a fact everyone must accept.']],
[['What helped the second attempt?','Following one fold at a time','Using no paper','Ignoring the cousin','The cousin modeled the folds and the writer pressed them carefully.'],['Which detail shows a feeling?','I felt proud','I opened a fresh sheet','I wrote the steps','Felt proud directly describes the writer’s emotional response.']],
[['Which task is editing?','Checking capitals and the period','Choosing a more specific animal','Adding where the rabbit went','Editing checks conventions; adding useful detail is revision.'],['Why is the second sentence clearer?','It names the animal, action, and place','It removes the action','It uses no spaces','Specific details make the action easier to picture.']],
[['Why did Noor name the book used?','To identify a source','To hide the drawing','To avoid explaining the plant','Naming a source helps listeners understand where information came from.'],['Which is a useful visitor question?','What evidence helped you reach that idea?','Why is every display identical?','Can we ignore the labels?','Asking about evidence supports discussion of the learning.']]
];
const science=[
['Could the same objects be sorted two ways?','Yes, by two different properties','No, every object has only one property','Only if their material changes','An object can have several observable properties.'],
['Which material should a rain cover use?','One that resists water','One that quickly absorbs all water','One that dissolves in rain','The intended job determines which property is useful.'],
['What evidence shows the same pieces were reused?','The before-and-after counts both show six blocks','The models have different heights','The new model has a name','Matching piece counts help show no blocks were added or removed.'],
['Why is melting ice different from baking dough?','Water can freeze again, but baking is not easily reversed','Both always reverse by waiting','Neither changes a material','The lesson contrasts a reversible change with one not easily reversed.'],
['What should you record in a plant investigation?','Observations over several days','Only the result you hoped for','Only the color of your pencil','Records over time help show growth and change.'],
['What is a limit of a paper-seed model?','It does not include every feature of a real seed','It proves all seeds travel the same way','It is exactly the same as every seed','Models represent selected features, not every part of reality.'],
['Do all flowers depend on animals to move pollen?','No, wind moves pollen for some plants','Yes, every flower needs the same animal','No plant ever uses animals','The passage describes both animal and wind pollination.'],
['What can an observation list show?','Living things seen during the observation','Every organism that has ever lived there','Exactly what will be there next year','The list is limited to what the observer noticed at that time.'],
['Why use more than color to compare organisms?','Color alone may not identify their kind','All organisms have the same color','Color tells every detail','Other observable features provide additional evidence.'],
['How can people study a very slow landscape change?','Compare images taken at different times','Assume no change is possible','Watch one second and stop','Images across time can reveal changes too slow for a brief visit.'],
['What could reduce soil moved by flowing water?','A tested barrier','Adding unlimited water','Ignoring the slope','Barriers are one possible solution that can be compared in a model.'],
['Why add a key to a map model?','To explain its symbols','To make every feature life-size','To remove the need for labels','A key helps readers interpret symbols.'],
['Where is most of Earth’s water?','In salty oceans','In kitchen cups','In the one nearest pond','The lesson identifies oceans as the largest water store.'],
['Which is a design limit?','Only two sheets of paper are available','The holder must work','The toy should stay upright','Available materials constrain the solution.'],
['What can arrows show on a sketch?','How a part moves','The exact age of the inventor','Every future test result','Arrows can communicate motion or direction.'],
['Why repeat a design test?','To see whether the result is consistent','To guarantee success','To avoid recording evidence','A single trial may not show how reliably a design works.'],
['What connects a claim to its evidence?','Reasoning','A larger title','A guess without explanation','Reasoning explains why observations support the claim.'],
['What should you do if new evidence disagrees with your explanation?','Reconsider the explanation','Hide the new evidence','Stop asking questions forever','Explanations can change when evidence changes.']
];
const social=[
['Can a person belong to more than one community?','Yes, communities can overlap','No, only one is possible','Only if they own every building','A person can belong to communities connected by different purposes.'],
['Why compare more than one photograph?','One image cannot show every experience','All images are always identical','Only the newest image counts','Multiple sources can add information and reveal limits.'],
['What does a timeline leave out?','Many events not selected for it','All order','Every date','A timeline chooses events rather than showing everything.'],
['What if someone does not want to answer an interview question?','Respect their choice','Keep asking until they agree','Invent an answer for them','Participation and personal boundaries should be respected.'],
['How could you decide whether a rule helps?','Observe whether it serves its purpose fairly','Count its letters only','Assume every rule is perfect','Evidence about effects helps evaluate a rule.'],
['Why consider whether everyone can join the chosen game?','Participation needs matter in a shared decision','Only winning matters','A vote removes every other concern','A fair process considers access and basic needs.'],
['Can useful community work be unpaid?','Yes, people also give unpaid help','No, only paid work helps','Only if no one notices','The lesson includes help at home and in the community.'],
['Can someone’s needs depend on their situation?','Yes, situations can change needs','No, everyone needs identical things at every moment','Only wants can ever change','The lesson asks us to consider different situations.'],
['Why ask several people about a new bus route?','The change may affect them differently','Everyone always has the same experience','Only one person uses roads','Different accounts help reveal benefits and concerns.'],
['Why does a room map leave out small details?','It selects what is useful for its purpose','It is always a mistake','Maps cannot use symbols','A useful map simplifies a place to answer a question.'],
['Should you assume a symbol means the same thing on every map?','No, check each map’s key','Yes, keys never matter','Only if the symbol is blue','Keys define symbols for the particular map.'],
['Why can left differ from west?','Left depends on which way you face','West changes every minute','Left is always north','Relative and cardinal directions describe orientation differently.'],
['How does a river differ from a lake?','A river flows along a channel','A river is always dry','A lake is a mountain','The lesson distinguishes flowing channels from inland bodies of water.'],
['How is a country different from a continent?','A country has political boundaries; a continent is a large land region','They are always the same area','Countries are always oceans','The terms describe different kinds of regions.'],
['Can a five-day chart describe a place’s whole climate?','No, climate concerns much longer patterns','Yes, five days show all years','Only if the chart is colorful','A short weather record is not a long-term climate record.'],
['What is a trade-off in a land-use choice?','A benefit that comes with giving up another possible use','A choice with no effects','A rule that no one can discuss','Limited space means one use may reduce space for another.'],
['How can a book connect places?','It can carry ideas from a writer to distant readers','It moves every reader to the same town','It changes all roads','Connections include movement of ideas as well as goods.'],
['Why use maps at different scales?','They show different levels of detail','They all answer only the same question','Small-scale world maps show every door','A local route and a global relationship need different detail.']
];
function item(row,turn){const options=row.slice(1,4),right=options[0],offset=turn%3;const rotated=options.slice(offset).concat(options.slice(0,offset));return{question:row[0],options:rotated,answer:rotated.indexOf(right),explanation:row[4]};}
function attach(id,rows,index){const l=C.lessons.find(l=>l.id===id);if(!l)throw Error('Missing lesson '+id);const base=l.kind==='book'?l.book:l;l.questions=[{question:base.question,options:base.options,answer:base.answer,explanation:base.explanation},...rows.map((r,j)=>item(r,index+j+1))];}
reading.forEach((r,i)=>attach(`year2-r-${i+1}`,r,i));science.forEach((r,i)=>attach(`year2-s-${i+1}`,[r],i));social.forEach((r,i)=>attach(`year2-h-${i+1}`,[r],i));
})(typeof globalThis!=='undefined'?globalThis:this);
